<?php
/**
 * Kaptor - Paletas de color: cinco oscuras y cinco claras.
 *
 * Cada paleta es un tema completo, no solo un acento: define el degradado
 * del fondo, el color del texto y dos acentos (el principal forma a su vez
 * un degradado con 'oro2'), y lo hace para los DOS modos, porque el
 * visitante puede cambiar de modo con el botón de la cabecera.
 *
 *   fondo / fondo2 / texto                          modo oscuro
 *   oro / oro2 / neon                               acentos del modo oscuro
 *   fondo_claro / fondo2_claro / texto_claro        modo claro
 *   oro_claro / oro2_claro / neon_claro             acentos del modo claro
 *
 * El campo 'modo' dice cuál de los dos se deja puesto al elegir la paleta.
 * Todas las combinaciones están comprobadas por encima del contraste AA de
 * la WCAG, contra los dos extremos del degradado del fondo.
 *
 * Para añadir un tema propio basta con copiar una entrada y cambiar los
 * valores: aparece solo en Ajustes > Apariencia.
 */
declare(strict_types=1);

return [
    'onice' => [
        'nombre'        => 'Ónice y oro',
        'pista'         => 'Negro profundo con veta de oro y verde esmeralda.',
        'modo'          => 'oscuro',
        'fondo'         => '#07070A',
        'fondo2'        => '#161008',
        'texto'         => '#F4F2EC',
        'oro'           => '#E8C275',
        'oro2'          => '#B8873A',
        'neon'          => '#5BE3A0',
        'fondo_claro'   => '#FCFAF4',
        'fondo2_claro'  => '#F3EAD8',
        'texto_claro'   => '#171308',
        'oro_claro'     => '#856212',
        'oro2_claro'    => '#856319',
        'neon_claro'    => '#0F6E44',
    ],
    'zafiro' => [
        'nombre'        => 'Zafiro',
        'pista'         => 'Azul marino profundo con destello eléctrico.',
        'modo'          => 'oscuro',
        'fondo'         => '#04081C',
        'fondo2'        => '#0A1440',
        'texto'         => '#EDF1FF',
        'oro'           => '#6BA5FF',
        'oro2'          => '#447AFF',
        'neon'          => '#3FE4E4',
        'fondo_claro'   => '#F7FAFF',
        'fondo2_claro'  => '#E4ECFF',
        'texto_claro'   => '#0A1128',
        'oro_claro'     => '#1D4ED8',
        'oro2_claro'    => '#1E40AF',
        'neon_claro'    => '#0C6E74',
    ],
    'amatista' => [
        'nombre'        => 'Amatista',
        'pista'         => 'Púrpura de joya con brillo fucsia.',
        'modo'          => 'oscuro',
        'fondo'         => '#0A0518',
        'fondo2'        => '#1D0A3C',
        'texto'         => '#F3EDFF',
        'oro'           => '#C084FC',
        'oro2'          => '#F065C8',
        'neon'          => '#42D9F0',
        'fondo_claro'   => '#FBF8FF',
        'fondo2_claro'  => '#EFE4FF',
        'texto_claro'   => '#180C2E',
        'oro_claro'     => '#6D28D9',
        'oro2_claro'    => '#8E32E1',
        'neon_claro'    => '#A21657',
    ],
    'rubi' => [
        'nombre'        => 'Rubí',
        'pista'         => 'Granate encendido con reflejos ámbar.',
        'modo'          => 'oscuro',
        'fondo'         => '#0F0407',
        'fondo2'        => '#320A14',
        'texto'         => '#FFEEF0',
        'oro'           => '#FF5470',
        'oro2'          => '#FF9A3C',
        'neon'          => '#FFC857',
        'fondo_claro'   => '#FFF8F8',
        'fondo2_claro'  => '#FFE7E9',
        'texto_claro'   => '#24090E',
        'oro_claro'     => '#B3122E',
        'oro2_claro'    => '#BB3F0C',
        'neon_claro'    => '#8A5A00',
    ],
    'esmeralda' => [
        'nombre'        => 'Esmeralda',
        'pista'         => 'Verde bosque profundo con lima y menta.',
        'modo'          => 'oscuro',
        'fondo'         => '#03120C',
        'fondo2'        => '#062B1E',
        'texto'         => '#E9FAF1',
        'oro'           => '#3FE08C',
        'oro2'          => '#A8E85A',
        'neon'          => '#4FD9D9',
        'fondo_claro'   => '#F6FCF8',
        'fondo2_claro'  => '#E1F5EA',
        'texto_claro'   => '#0A1F14',
        'oro_claro'     => '#0F7A46',
        'oro2_claro'    => '#48780F',
        'neon_claro'    => '#0B6E70',
    ],
    'marfil' => [
        'nombre'        => 'Marfil y oro',
        'pista'         => 'Papel cálido, oro viejo y verde botella. Señorial.',
        'modo'          => 'claro',
        'fondo'         => '#12100B',
        'fondo2'        => '#241D10',
        'texto'         => '#F6F2E6',
        'oro'           => '#E3C27E',
        'oro2'          => '#C29A45',
        'neon'          => '#5FD1A0',
        'fondo_claro'   => '#FDFBF4',
        'fondo2_claro'  => '#F4EBD6',
        'texto_claro'   => '#191509',
        'oro_claro'     => '#886210',
        'oro2_claro'    => '#836316',
        'neon_claro'    => '#0E6B45',
    ],
    'perla' => [
        'nombre'        => 'Perla y zafiro',
        'pista'         => 'Blanco frío con azul profundo. Aire corporativo.',
        'modo'          => 'claro',
        'fondo'         => '#080C18',
        'fondo2'        => '#111A33',
        'texto'         => '#EEF2FA',
        'oro'           => '#7FB0FF',
        'oro2'          => '#4F7EFF',
        'neon'          => '#3ED0D0',
        'fondo_claro'   => '#FAFCFF',
        'fondo2_claro'  => '#E8EFFA',
        'texto_claro'   => '#0C1524',
        'oro_claro'     => '#15489E',
        'oro2_claro'    => '#1D4ED8',
        'neon_claro'    => '#0A6A70',
    ],
    'orquidea' => [
        'nombre'        => 'Orquídea',
        'pista'         => 'Lila muy claro con violeta intenso y fucsia.',
        'modo'          => 'claro',
        'fondo'         => '#120A1E',
        'fondo2'        => '#221038',
        'texto'         => '#F3ECFC',
        'oro'           => '#C99CFF',
        'oro2'          => '#F07CE0',
        'neon'          => '#4FD6EE',
        'fondo_claro'   => '#FCFAFF',
        'fondo2_claro'  => '#F0E8FB',
        'texto_claro'   => '#1A1128',
        'oro_claro'     => '#6B21A8',
        'oro2_claro'    => '#A21CAF',
        'neon_claro'    => '#9D174D',
    ],
    'coral' => [
        'nombre'        => 'Coral',
        'pista'         => 'Blanco cálido con rosa coral y naranja.',
        'modo'          => 'claro',
        'fondo'         => '#170A0E',
        'fondo2'        => '#2C1016',
        'texto'         => '#FBEDEF',
        'oro'           => '#FF7B94',
        'oro2'          => '#FFA76B',
        'neon'          => '#FFCF6B',
        'fondo_claro'   => '#FFFAF8',
        'fondo2_claro'  => '#FDE9E4',
        'texto_claro'   => '#20101A',
        'oro_claro'     => '#B81653',
        'oro2_claro'    => '#BB3F0C',
        'neon_claro'    => '#8A5A00',
    ],
    'jade' => [
        'nombre'        => 'Jade',
        'pista'         => 'Menta muy clara con verde jade y turquesa.',
        'modo'          => 'claro',
        'fondo'         => '#06130F',
        'fondo2'        => '#0B2A22',
        'texto'         => '#E9F7F2',
        'oro'           => '#57D9A8',
        'oro2'          => '#8DE06A',
        'neon'          => '#46CFD4',
        'fondo_claro'   => '#F8FDFB',
        'fondo2_claro'  => '#E2F4EC',
        'texto_claro'   => '#0C1F18',
        'oro_claro'     => '#0B6E52',
        'oro2_claro'    => '#3E7817',
        'neon_claro'    => '#0B6A76',
    ],
];
