<?php
/**
 * Kaptor - Paletas de color: cinco oscuras y cinco claras.
 *
 * La idea es simple: la página es blanca (temas claros) o negra (temas
 * oscuros), y el color lo pone el acento. Por eso todos los temas oscuros
 * comparten el mismo negro y todos los claros el mismo blanco; lo que
 * cambia de uno a otro es el color con el que se pintan botones, enlaces,
 * bordes, halos y el radar.
 *
 *   fondo / fondo2 / texto                     página en modo oscuro
 *   oro / oro2 / neon                          acentos del modo oscuro
 *   fondo_claro / fondo2_claro / texto_claro   página en modo claro
 *   oro_claro / oro2_claro / neon_claro        acentos del modo claro
 *
 * El campo 'modo' dice cuál de los dos se deja puesto al elegir la paleta;
 * el visitante puede cambiarlo con el botón de la cabecera. Todas las
 * combinaciones están comprobadas por encima del contraste AA de la WCAG.
 *
 * Para añadir un tema propio basta con copiar una entrada y cambiar los
 * valores: aparece solo en Ajustes > Apariencia.
 */
declare(strict_types=1);

return [
    /* La paleta de la casa: papel blanco, tinta profunda, azul de marca.
       Va la primera porque es la que se lleva puesta de serie. */
    'tinta' => [
        'nombre'        => 'Tinta',
        'pista'         => 'Página blanca, tinta profunda y azul de marca. La de la casa.',
        'modo'          => 'claro',
        'fondo'         => '#0B0D11',
        'fondo2'        => '#11141A',
        'texto'         => '#EDEFF3',
        'oro'           => '#7DA2FF',
        'oro2'          => '#A8C0FF',
        'neon'          => '#43D98B',
        'fondo_claro'   => '#FFFFFF',
        'fondo2_claro'  => '#F7F8FA',
        'texto_claro'   => '#0E1116',
        'oro_claro'     => '#133E92',
        'oro2_claro'    => '#072B72',
        'neon_claro'    => '#0F7B43',
        'acento_claro'  => '#FF4800',
        'acento'        => '#FF6A33',
    ],
    'azul' => [
        'nombre'        => 'Azul eléctrico',
        'pista'         => 'Negro puro con azul intenso y turquesa.',
        'modo'          => 'oscuro',
        'fondo'         => '#06070A',
        'fondo2'        => '#0D0F14',
        'texto'         => '#F2F4F7',
        'oro'           => '#3B82F6',
        'oro2'          => '#22D3EE',
        'neon'          => '#38BDF8',
        'fondo_claro'   => '#FFFFFF',
        'fondo2_claro'  => '#F4F6FA',
        'texto_claro'   => '#111418',
        'oro_claro'     => '#336CCA',
        'oro2_claro'    => '#1A7787',
        'neon_claro'    => '#28769A',
    ],
    'rojo' => [
        'nombre'        => 'Rojo',
        'pista'         => 'Negro puro con rojo encendido y naranja.',
        'modo'          => 'oscuro',
        'fondo'         => '#06070A',
        'fondo2'        => '#0D0F14',
        'texto'         => '#F2F4F7',
        'oro'           => '#EF4444',
        'oro2'          => '#F97316',
        'neon'          => '#FB7185',
        'fondo_claro'   => '#FFFFFF',
        'fondo2_claro'  => '#F4F6FA',
        'texto_claro'   => '#111418',
        'oro_claro'     => '#C73B3C',
        'oro2_claro'    => '#AF5517',
        'neon_claro'    => '#AC5160',
    ],
    'turquesa' => [
        'nombre'        => 'Turquesa',
        'pista'         => 'Negro puro con turquesa y verde menta.',
        'modo'          => 'oscuro',
        'fondo'         => '#06070A',
        'fondo2'        => '#0D0F14',
        'texto'         => '#F2F4F7',
        'oro'           => '#14C8C0',
        'oro2'          => '#2FD98E',
        'neon'          => '#22D3EE',
        'fondo_claro'   => '#FFFFFF',
        'fondo2_claro'  => '#F4F6FA',
        'texto_claro'   => '#111418',
        'oro_claro'     => '#137C79',
        'oro2_claro'    => '#227E58',
        'neon_claro'    => '#1A7787',
    ],
    'violeta' => [
        'nombre'        => 'Violeta',
        'pista'         => 'Negro puro con violeta y fucsia.',
        'modo'          => 'oscuro',
        'fondo'         => '#06070A',
        'fondo2'        => '#0D0F14',
        'texto'         => '#F2F4F7',
        'oro'           => '#9063F6',
        'oro2'          => '#D946C8',
        'neon'          => '#A78BFA',
        'fondo_claro'   => '#FFFFFF',
        'fondo2_claro'  => '#F4F6FA',
        'texto_claro'   => '#111418',
        'oro_claro'     => '#7C53DB',
        'oro2_claro'    => '#B53DA8',
        'neon_claro'    => '#7463AD',
    ],
    'oro' => [
        'nombre'        => 'Oro',
        'pista'         => 'Negro puro con oro champán y ámbar.',
        'modo'          => 'oscuro',
        'fondo'         => '#06070A',
        'fondo2'        => '#0D0F14',
        'texto'         => '#F2F4F7',
        'oro'           => '#D8B36A',
        'oro2'          => '#B8873A',
        'neon'          => '#F0C674',
        'fondo_claro'   => '#FFFFFF',
        'fondo2_claro'  => '#F4F6FA',
        'texto_claro'   => '#111418',
        'oro_claro'     => '#816D46',
        'oro2_claro'    => '#8D6931',
        'neon_claro'    => '#816D46',
    ],
    'azul-claro' => [
        'nombre'        => 'Azul',
        'pista'         => 'Página blanca con azul intenso y celeste.',
        'modo'          => 'claro',
        'fondo'         => '#06070A',
        'fondo2'        => '#0D0F14',
        'texto'         => '#F2F4F7',
        'oro'           => '#587CE2',
        'oro2'          => '#0786C8',
        'neon'          => '#3084B2',
        'fondo_claro'   => '#FFFFFF',
        'fondo2_claro'  => '#F4F6FA',
        'texto_claro'   => '#111418',
        'oro_claro'     => '#1D4ED8',
        'oro2_claro'    => '#0474AE',
        'neon_claro'    => '#0369A1',
    ],
    'rojo-claro' => [
        'nombre'        => 'Rojo',
        'pista'         => 'Página blanca con rojo intenso y naranja.',
        'modo'          => 'claro',
        'fondo'         => '#06070A',
        'fondo2'        => '#0D0F14',
        'texto'         => '#F2F4F7',
        'oro'           => '#D55464',
        'oro2'          => '#D75622',
        'neon'          => '#C06167',
        'fondo_claro'   => '#FFFFFF',
        'fondo2_claro'  => '#F4F6FA',
        'texto_claro'   => '#111418',
        'oro_claro'     => '#C81E33',
        'oro2_claro'    => '#C44310',
        'neon_claro'    => '#A3161F',
    ],
    'turquesa-claro' => [
        'nombre'        => 'Turquesa',
        'pista'         => 'Página blanca con turquesa y verde.',
        'modo'          => 'claro',
        'fondo'         => '#06070A',
        'fondo2'        => '#0D0F14',
        'texto'         => '#F2F4F7',
        'oro'           => '#2B8C95',
        'oro2'          => '#0F8F6A',
        'neon'          => '#37888D',
        'fondo_claro'   => '#FFFFFF',
        'fondo2_claro'  => '#F4F6FA',
        'texto_claro'   => '#111418',
        'oro_claro'     => '#0E7A84',
        'oro2_claro'    => '#0F7E5F',
        'neon_claro'    => '#0B6E74',
    ],
    'violeta-claro' => [
        'nombre'        => 'Violeta',
        'pista'         => 'Página blanca con violeta y magenta.',
        'modo'          => 'claro',
        'fondo'         => '#06070A',
        'fondo2'        => '#0D0F14',
        'texto'         => '#F2F4F7',
        'oro'           => '#9664E4',
        'oro2'          => '#BA57C4',
        'neon'          => '#A260DC',
        'fondo_claro'   => '#FFFFFF',
        'fondo2_claro'  => '#F4F6FA',
        'texto_claro'   => '#111418',
        'oro_claro'     => '#6D28D9',
        'oro2_claro'    => '#A21CAF',
        'neon_claro'    => '#7E22CE',
    ],
    'verde-claro' => [
        'nombre'        => 'Verde',
        'pista'         => 'Página blanca con verde intenso y lima.',
        'modo'          => 'claro',
        'fondo'         => '#06070A',
        'fondo2'        => '#0D0F14',
        'texto'         => '#F2F4F7',
        'oro'           => '#318F54',
        'oro2'          => '#628C2C',
        'neon'          => '#358C85',
        'fondo_claro'   => '#FFFFFF',
        'fondo2_claro'  => '#F4F6FA',
        'texto_claro'   => '#111418',
        'oro_claro'     => '#15803D',
        'oro2_claro'    => '#4D7C0F',
        'neon_claro'    => '#0F766E',
    ],
];
