<?php
/**
 * Kaptor - Paletas de color listas para usar: diez oscuras y diez claras.
 *
 * Cada paleta define los colores de los DOS modos, porque el visitante puede
 * cambiar de modo con el botón de la cabecera. El campo 'modo' solo dice cuál
 * es el que se deja puesto al elegir la paleta en el panel.
 *
 *   fondo / texto                         modo oscuro
 *   fondo_claro / texto_claro             modo claro
 *   oro / oro2 / neon                     acentos del modo oscuro
 *                                         (oro y oro2 forman el degradado)
 *   oro_claro / oro2_claro / neon_claro   los mismos acentos, para el claro
 *
 * Todas las combinaciones están comprobadas por encima del contraste AA de
 * la WCAG. Para añadir un tema propio basta con copiar una entrada y cambiar
 * los valores: aparece solo en Ajustes > Apariencia.
 */
declare(strict_types=1);

return [
    'obsidiana' => [
        'nombre'      => 'Obsidiana y oro',
        'pista'       => 'Negro volcánico, oro champán y verde fósforo.',
        'modo'        => 'oscuro',
        'fondo'       => '#07080A',
        'texto'       => '#F3F4F6',
        'fondo_claro' => '#FBF8F0',
        'texto_claro' => '#171512',
        'oro'         => '#D8B36A',
        'oro2'        => '#F3D89A',
        'neon'        => '#6EF3A5',
        'oro_claro'   => '#846E43',
        'oro2_claro'  => '#7D6F51',
        'neon_claro'  => '#3E7C56',
    ],
    'magenta' => [
        'nombre'      => 'Magenta eléctrico',
        'pista'       => 'Rosa de neón sobre tinta morada. Muy llamativo.',
        'modo'        => 'oscuro',
        'fondo'       => '#0B0410',
        'texto'       => '#F9F2FB',
        'fondo_claro' => '#FCF3FA',
        'texto_claro' => '#1A1020',
        'oro'         => '#FF2E88',
        'oro2'        => '#A855F7',
        'neon'        => '#00E5FF',
        'oro_claro'   => '#CE286F',
        'oro2_claro'  => '#924BD4',
        'neon_claro'  => '#0A7985',
    ],
    'cian' => [
        'nombre'      => 'Cian nitro',
        'pista'       => 'Azul eléctrico y verde lima. Aire de pantalla de radar.',
        'modo'        => 'oscuro',
        'fondo'       => '#03121A',
        'texto'       => '#EAF7FB',
        'fondo_claro' => '#EFF8FC',
        'texto_claro' => '#0C1A22',
        'oro'         => '#00E5FF',
        'oro2'        => '#4BFF9E',
        'neon'        => '#8BFF3D',
        'oro_claro'   => '#0A7985',
        'oro2_claro'  => '#2D7D50',
        'neon_claro'  => '#487A24',
    ],
    'lava' => [
        'nombre'      => 'Lava',
        'pista'       => 'Naranja incandescente con destellos ámbar.',
        'modo'        => 'oscuro',
        'fondo'       => '#120604',
        'texto'       => '#FFF2EA',
        'fondo_claro' => '#FFF5EE',
        'texto_claro' => '#1E120B',
        'oro'         => '#FF6B1A',
        'oro2'        => '#FFD400',
        'neon'        => '#FFD400',
        'oro_claro'   => '#B85017',
        'oro2_claro'  => '#826D08',
        'neon_claro'  => '#826D08',
    ],
    'violeta' => [
        'nombre'      => 'Violeta ultra',
        'pista'       => 'Púrpura intenso y turquesa. Elegante y moderno.',
        'modo'        => 'oscuro',
        'fondo'       => '#0A0614',
        'texto'       => '#F2EEFF',
        'fondo_claro' => '#F6F2FD',
        'texto_claro' => '#171227',
        'oro'         => '#B472FF',
        'oro2'        => '#FF6EC7',
        'neon'        => '#22D3EE',
        'oro_claro'   => '#8757BC',
        'oro2_claro'  => '#AA4D85',
        'neon_claro'  => '#1B7886',
    ],
    'neon' => [
        'nombre'      => 'Verde neón',
        'pista'       => 'Verde fluorescente puro sobre negro. Estilo terminal.',
        'modo'        => 'oscuro',
        'fondo'       => '#04120A',
        'texto'       => '#EAFBEF',
        'fondo_claro' => '#F0FAF2',
        'texto_claro' => '#0D1A12',
        'oro'         => '#4BFF5A',
        'oro2'        => '#00E5FF',
        'neon'        => '#00E5FF',
        'oro_claro'   => '#2D7F32',
        'oro2_claro'  => '#0A7C88',
        'neon_claro'  => '#0A7C88',
    ],
    'carmesi' => [
        'nombre'      => 'Carmesí',
        'pista'       => 'Rojo encendido con ámbar. Urgente y potente.',
        'modo'        => 'oscuro',
        'fondo'       => '#120306',
        'texto'       => '#FFEDF0',
        'fondo_claro' => '#FFF2F4',
        'texto_claro' => '#1D0F12',
        'oro'         => '#FF3B5C',
        'oro2'        => '#FF9A3D',
        'neon'        => '#FFB020',
        'oro_claro'   => '#CE324C',
        'oro2_claro'  => '#9C612A',
        'neon_claro'  => '#916618',
    ],
    'cobalto' => [
        'nombre'      => 'Cobalto',
        'pista'       => 'Azul corporativo saturado con acento turquesa.',
        'modo'        => 'oscuro',
        'fondo'       => '#04091A',
        'texto'       => '#ECF2FF',
        'fondo_claro' => '#F0F4FD',
        'texto_claro' => '#0E1526',
        'oro'         => '#5B9BFF',
        'oro2'        => '#22D3EE',
        'neon'        => '#22D3EE',
        'oro_claro'   => '#446EB0',
        'oro2_claro'  => '#1B7886',
        'neon_claro'  => '#1B7886',
    ],
    'voltaje' => [
        'nombre'      => 'Alto voltaje',
        'pista'       => 'Amarillo señal y naranja. Máxima visibilidad.',
        'modo'        => 'oscuro',
        'fondo'       => '#0D0C02',
        'texto'       => '#FFFCE6',
        'fondo_claro' => '#FDFBEC',
        'texto_claro' => '#17150A',
        'oro'         => '#FFE100',
        'oro2'        => '#FF6A00',
        'neon'        => '#FF6A00',
        'oro_claro'   => '#807109',
        'oro2_claro'  => '#BD5104',
        'neon_claro'  => '#BD5104',
    ],
    'synthwave' => [
        'nombre'      => 'Synthwave',
        'pista'       => 'Rosa chicle y violeta de los ochenta.',
        'modo'        => 'oscuro',
        'fondo'       => '#0C0418',
        'texto'       => '#FBEEFF',
        'fondo_claro' => '#FAF1FD',
        'texto_claro' => '#180F24',
        'oro'         => '#FF5FDC',
        'oro2'        => '#8B6BFF',
        'neon'        => '#8B6BFF',
        'oro_claro'   => '#AF4597',
        'oro2_claro'  => '#745AD2',
        'neon_claro'  => '#745AD2',
    ],
    'marfil' => [
        'nombre'      => 'Marfil y oro',
        'pista'       => 'Papel cálido con oro viejo. Sobrio y señorial.',
        'modo'        => 'claro',
        'fondo'       => '#0B0906',
        'texto'       => '#F5F1E6',
        'fondo_claro' => '#FBF7EE',
        'texto_claro' => '#17150F',
        'oro'         => '#C5AF82',
        'oro2'        => '#B5A788',
        'neon'        => '#84BAA2',
        'oro_claro'   => '#8F650F',
        'oro2_claro'  => '#6B4F12',
        'neon_claro'  => '#127A4C',
    ],
    'porcelana' => [
        'nombre'      => 'Porcelana y azul',
        'pista'       => 'Blanco frío con azul intenso. Aire corporativo.',
        'modo'        => 'claro',
        'fondo'       => '#060A14',
        'texto'       => '#EEF3FB',
        'fondo_claro' => '#F4F7FC',
        'texto_claro' => '#101827',
        'oro'         => '#89A3EB',
        'oro2'        => '#81B4D0',
        'neon'        => '#80B4B4',
        'oro_claro'   => '#1D4ED8',
        'oro2_claro'  => '#0369A1',
        'neon_claro'  => '#0B6E6E',
    ],
    'menta' => [
        'nombre'      => 'Menta fresca',
        'pista'       => 'Verde limpio sobre blanco. Ligero y fresco.',
        'modo'        => 'claro',
        'fondo'       => '#04140D',
        'texto'       => '#EAF7F0',
        'fondo_claro' => '#F1FAF5',
        'texto_claro' => '#0E2018',
        'oro'         => '#7CB9A8',
        'oro2'        => '#87BAB6',
        'neon'        => '#7CB1CE',
        'oro_claro'   => '#047857',
        'oro2_claro'  => '#0F766E',
        'neon_claro'  => '#0369A1',
    ],
    'lavanda' => [
        'nombre'      => 'Lavanda',
        'pista'       => 'Violeta suave con acento fucsia. Delicado.',
        'modo'        => 'claro',
        'fondo'       => '#0D0819',
        'texto'       => '#F1EDFB',
        'fondo_claro' => '#F6F3FD',
        'texto_claro' => '#191231',
        'oro'         => '#B38FEB',
        'oro2'        => '#BE90E6',
        'neon'        => '#DD87AB',
        'oro_claro'   => '#6D28D9',
        'oro2_claro'  => '#7E22CE',
        'neon_claro'  => '#BE185D',
    ],
    'arena' => [
        'nombre'      => 'Arena y terracota',
        'pista'       => 'Tonos cálidos de barro cocido. Acogedor.',
        'modo'        => 'claro',
        'fondo'       => '#140C07',
        'texto'       => '#F6EDE4',
        'fondo_claro' => '#FBF4EE',
        'texto_claro' => '#211610',
        'oro'         => '#D69980',
        'oro2'        => '#C8A086',
        'neon'        => '#82B4AE',
        'oro_claro'   => '#B03A0B',
        'oro2_claro'  => '#92400E',
        'neon_claro'  => '#0F6E63',
    ],
    'perla' => [
        'nombre'      => 'Perla y carmesí',
        'pista'       => 'Gris nacarado con rojo intenso. Con carácter.',
        'modo'        => 'claro',
        'fondo'       => '#100C0F',
        'texto'       => '#F2EFF1',
        'fondo_claro' => '#F7F5F6',
        'texto_claro' => '#1A1418',
        'oro'         => '#E08A8F',
        'oro2'        => '#CF889C',
        'neon'        => '#9D98E3',
        'oro_claro'   => '#C41E28',
        'oro2_claro'  => '#9F1239',
        'neon_claro'  => '#4338CA',
    ],
    'grafito' => [
        'nombre'      => 'Nieve y grafito',
        'pista'       => 'Monocromo elegante con un azul de apoyo.',
        'modo'        => 'claro',
        'fondo'       => '#0B111E',
        'texto'       => '#EFF2F7',
        'fondo_claro' => '#F7F8FA',
        'texto_claro' => '#0F172A',
        'oro'         => '#8B9097',
        'oro2'        => '#9BA0A8',
        'neon'        => '#89A3EB',
        'oro_claro'   => '#1F2937',
        'oro2_claro'  => '#374151',
        'neon_claro'  => '#1D4ED8',
    ],
    'coral' => [
        'nombre'      => 'Coral',
        'pista'       => 'Rosa coral sobre blanco cálido. Moderno.',
        'modo'        => 'claro',
        'fondo'       => '#150910',
        'texto'       => '#FAEDE9',
        'fondo_claro' => '#FFF5F2',
        'texto_claro' => '#24121A',
        'oro'         => '#E788AB',
        'oro2'        => '#CE8BA6',
        'neon'        => '#B38FEB',
        'oro_claro'   => '#D01B5E',
        'oro2_claro'  => '#9D174D',
        'neon_claro'  => '#6D28D9',
    ],
    'bosque' => [
        'nombre'      => 'Crema y bosque',
        'pista'       => 'Verde profundo sobre crema. Natural y serio.',
        'modo'        => 'claro',
        'fondo'       => '#0B120A',
        'texto'       => '#EEF2E7',
        'fondo_claro' => '#F5F7F0',
        'texto_claro' => '#15200F',
        'oro'         => '#85BD9A',
        'oro2'        => '#9FB088',
        'neon'        => '#BFAD7E',
        'oro_claro'   => '#15803D',
        'oro2_claro'  => '#3F6212',
        'neon_claro'  => '#846107',
    ],
    'cielo' => [
        'nombre'      => 'Cielo',
        'pista'       => 'Azul claro luminoso con violeta de apoyo.',
        'modo'        => 'claro',
        'fondo'       => '#061019',
        'texto'       => '#E9F2FB',
        'fondo_claro' => '#F0F7FF',
        'texto_claro' => '#0C1B2A',
        'oro'         => '#7CB1CE',
        'oro2'        => '#83ACC2',
        'neon'        => '#B38FEB',
        'oro_claro'   => '#0369A1',
        'oro2_claro'  => '#075985',
        'neon_claro'  => '#6D28D9',
    ],
];
