<?php
declare(strict_types=1);
error_reporting(E_ALL);
ini_set('display_errors', '1');

define('FL_APP', dirname(__DIR__) . '/app');
require FL_APP . '/helpers.php';
require FL_APP . '/Database.php';

$configFile = FL_APP . '/config.php';
$alreadyInstalled = is_file($configFile);

/* Requirement checks */
$requirements = [
    'PHP >= 8.0'          => version_compare(PHP_VERSION, '8.0.0', '>='),
    'Extensión PDO MySQL' => extension_loaded('pdo_mysql'),
    'Extensión fileinfo'  => extension_loaded('fileinfo'),
    'Extensión mbstring'  => extension_loaded('mbstring'),
    'Extensión GD (imágenes)' => extension_loaded('gd'),
    'app/ escribible'     => is_writable(FL_APP),
    'uploads/ escribible' => is_writable(dirname(__DIR__) . '/uploads'),
];
$reqOk = !in_array(false, array_slice($requirements, 0, 6, true), true); // GD optional-ish but recommended

$errors = [];
$done = false;

if (!$alreadyInstalled && ($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'POST') {
    $db = [
        'host'    => trim((string)($_POST['db_host'] ?? 'localhost')),
        'port'    => trim((string)($_POST['db_port'] ?? '3306')),
        'name'    => trim((string)($_POST['db_name'] ?? '')),
        'user'    => trim((string)($_POST['db_user'] ?? '')),
        'pass'    => (string)($_POST['db_pass'] ?? ''),
        'charset' => 'utf8mb4',
    ];
    $admin = [
        'name'     => trim((string)($_POST['admin_name'] ?? '')),
        'username' => trim((string)($_POST['admin_username'] ?? '')),
        'email'    => trim((string)($_POST['admin_email'] ?? '')),
        'password' => (string)($_POST['admin_password'] ?? ''),
    ];

    if ($db['name'] === '' || $db['user'] === '') { $errors[] = 'Complete los datos de la base de datos.'; }
    if ($admin['name'] === '' || $admin['username'] === '' || $admin['email'] === '') { $errors[] = 'Complete los datos del Super Administrador.'; }
    if (!filter_var($admin['email'], FILTER_VALIDATE_EMAIL)) { $errors[] = 'El correo del administrador no es válido.'; }
    if (strlen($admin['password']) < 8) { $errors[] = 'La contraseña debe tener al menos 8 caracteres.'; }

    $pdo = null;
    if (!$errors) {
        try {
            $pdo = Database::connect($db);
        } catch (Throwable $e) {
            $errors[] = 'No se pudo conectar a la base de datos: ' . $e->getMessage();
        }
    }

    if (!$errors && $pdo) {
        try {
            $pdo->exec("SET FOREIGN_KEY_CHECKS=0");
            foreach (require FL_APP . '/schema.php' as $sql) {
                $pdo->exec($sql);
            }
            $pdo->exec("SET FOREIGN_KEY_CHECKS=1");

            // Only seed if empty (idempotent-ish safety).
            $hasUsers = (int)$pdo->query("SELECT COUNT(*) FROM users")->fetchColumn();
            if ($hasUsers === 0) {
                require FL_APP . '/seed.php';
                fl_seed($pdo, $admin);
            }

            // Write config.php
            $salt = bin2hex(random_bytes(24));
            $cfg = "<?php\n// Generated by the installer. Keep this file private.\nreturn " . var_export([
                'db' => $db,
                'app' => ['installed' => true, 'base_url' => '', 'security_salt' => $salt],
            ], true) . ";\n";
            if (@file_put_contents($configFile, $cfg) === false) {
                $errors[] = 'No se pudo escribir app/config.php. Verifique permisos.';
            } else {
                @chmod($configFile, 0640);
                $done = true;
            }
        } catch (Throwable $e) {
            $errors[] = 'Error durante la instalación: ' . $e->getMessage();
        }
    }
}

// Default installer theme (Atlántico-like light).
$vars = '--c-bg:#0B0F14;--c-primary:#B6FF2E;--c-secondary:#FFFFFF;--c-accent:#6CFFB8;--c-surface:#141A21;--c-surface-2:#1D242D;--c-elevated:#232B35;--c-text:#F2F5F8;--c-text-on-surface:#F2F5F8;--c-text-muted:#9AA6B2;--c-text-subtle:#6B7683;--c-border:#232B35;--c-border-strong:#333D48;--c-on-primary:#0B0F14;--c-on-accent:#0B0F14;--c-link:#B6FF2E;--c-link-hover:#6CFFB8;--c-focus:#6CFFB8;--c-primary-rgb:182,255,46;--c-accent-rgb:108,255,184;--c-input-bg:#1D242D;--c-input-text:#F2F5F8;--c-input-border:#333D48;--c-shadow-rgb:0,0,0;--c-success:#16A34A;--c-warning:#D97706;--c-danger:#DC2626;--c-info:#2563EB;';
?><!DOCTYPE html>
<html lang="es">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex, nofollow">
<title>Instalación · Plataforma de Ligas de Fútbol</title>
<link rel="stylesheet" href="../assets/css/app.css">
<style>:root{<?= $vars ?>}</style>
</head>
<body>
<div class="login-wrap">
<div style="width:100%;max-width:640px">
    <div class="text-center mb-3">
        <div class="login-logo">⚽</div>
        <h1>Plataforma de Ligas de Fútbol</h1>
        <p class="muted">Asistente de instalación</p>
    </div>

    <?php if ($alreadyInstalled): ?>
        <div class="card card-pad-lg text-center">
            <div class="es-icon">✅</div>
            <h2>Ya está instalado</h2>
            <p class="muted">La plataforma ya fue instalada. Por seguridad, elimina la carpeta <code>/install</code>.</p>
            <a class="btn" href="../admin/login.php">Ir al panel</a>
        </div>
    <?php elseif ($done): ?>
        <div class="card card-pad-lg text-center">
            <div class="es-icon">🎉</div>
            <h2>¡Instalación completada!</h2>
            <p class="muted">Se crearon las tablas, el Super Administrador, los roles, permisos y los 10 temas visuales.
            No se cargó ninguna liga, equipo ni jugador de prueba.</p>
            <div class="alert alert-warning" style="text-align:left"><span><strong>Importante:</strong> Elimina la carpeta <code>/install</code> del servidor para mayor seguridad.</span></div>
            <a class="btn btn-lg" href="../admin/login.php">Acceder al panel</a>
        </div>
    <?php else: ?>
        <?php foreach ($errors as $er): ?><div class="alert alert-danger"><span><?= e($er) ?></span></div><?php endforeach; ?>

        <div class="card mb-3">
            <h3 style="margin-top:0">Requisitos del servidor</h3>
            <div class="detail-list">
                <?php foreach ($requirements as $label => $ok): ?>
                    <div class="row"><span class="k"><?= e($label) ?></span><span class="v"><?= $ok ? '<span class="badge badge-success">OK</span>' : '<span class="badge badge-danger">Falta</span>' ?></span></div>
                <?php endforeach; ?>
            </div>
        </div>

        <form method="post" class="card card-pad-lg">
            <h3 style="margin-top:0">Base de datos</h3>
            <div class="form-row">
                <div class="field"><label>Host</label><input class="input" name="db_host" value="<?= e($_POST['db_host'] ?? 'localhost') ?>" required></div>
                <div class="field"><label>Puerto</label><input class="input" name="db_port" value="<?= e($_POST['db_port'] ?? '3306') ?>"></div>
            </div>
            <div class="field"><label>Nombre de la base de datos</label><input class="input" name="db_name" value="<?= e($_POST['db_name'] ?? '') ?>" required></div>
            <div class="form-row">
                <div class="field"><label>Usuario</label><input class="input" name="db_user" value="<?= e($_POST['db_user'] ?? '') ?>" required></div>
                <div class="field"><label>Contraseña</label><input class="input" type="password" name="db_pass"></div>
            </div>

            <h3 class="mt-3">Super Administrador</h3>
            <div class="form-row">
                <div class="field"><label>Nombre completo</label><input class="input" name="admin_name" value="<?= e($_POST['admin_name'] ?? '') ?>" required></div>
                <div class="field"><label>Usuario</label><input class="input" name="admin_username" value="<?= e($_POST['admin_username'] ?? '') ?>" required></div>
            </div>
            <div class="field"><label>Correo electrónico</label><input class="input" type="email" name="admin_email" value="<?= e($_POST['admin_email'] ?? '') ?>" required></div>
            <div class="field"><label>Contraseña (mín. 8 caracteres)</label><input class="input" type="password" name="admin_password" required></div>

            <button class="btn btn-lg btn-block mt-2" type="submit"<?= $reqOk ? '' : ' disabled' ?>>Instalar plataforma</button>
            <?php if (!$reqOk): ?><p class="help text-center" style="color:var(--c-danger)">Corrige los requisitos faltantes antes de continuar.</p><?php endif; ?>
        </form>
    <?php endif; ?>
</div>
</div>
</body>
</html>
