<?php
declare(strict_types=1);

require __DIR__ . '/../lib/T.php';
require __DIR__ . '/a1_http.inc.php';
T::boot('a1_clients');

use App\Core\Db;
use App\Core\Tz;
use App\Services\BookingService;

A1Http::start(8116, '/tmp/ap-t-a1_clients.config.php');
$admin = new A1Client();
$admin->login('admin@test.local', 'Prueba#Segura2026');
$post = static function (string $form, string $path, array $data) use ($admin): array {
    return $admin->postForm($form, $path, $data);
};

T::section('Alta, edición y duplicados');
$r = $post('/admin/clientes/nuevo', '/admin/clientes/nuevo', ['name' => 'Ana Lucía Ruiz', 'email' => 'ANA@Example.test', 'phone' => '5533 4455', 'nit' => '1234567-8', 'tags' => 'vip, Recurrente, vip']);
T::eq(302, $r['status'], 'crea un cliente');
$id = (int) Db::val("SELECT id FROM clients WHERE email = 'ana@example.test'");
T::ok($id > 0, 'correo normalizado a minúsculas');
$c = Db::one('SELECT * FROM clients WHERE id = ?', [$id]);
T::eq('50255334455', $c['phone'], 'teléfono guardado con +502');
T::eq('vip, Recurrente', $c['tags'], 'etiquetas limpias y sin repetir');
$r = $post('/admin/clientes/nuevo', '/admin/clientes/nuevo', ['name' => 'Otra', 'email' => 'ana@example.test']);
T::eq(422, $r['status'], 'correo duplicado rechazado');
T::ok(str_contains($r['body'], 'Ya existe un cliente con ese correo'), 'mensaje de duplicado');
$r = $post('/admin/clientes/nuevo', '/admin/clientes/nuevo', ['name' => 'Otra', 'phone' => '5533 4455']);
T::eq(422, $r['status'], 'teléfono duplicado rechazado');
$r = $post('/admin/clientes/nuevo', '/admin/clientes/nuevo', ['name' => '', 'email' => 'x@example.test']);
T::eq(422, $r['status'], 'nombre obligatorio');
$r = $post('/admin/clientes/nuevo', '/admin/clientes/nuevo', ['name' => 'Mal', 'email' => 'no-es-correo']);
T::eq(422, $r['status'], 'correo inválido rechazado');
$r = $post("/admin/clientes/$id/editar", "/admin/clientes/$id/editar", ['name' => 'Ana Lucía R.', 'email' => 'ana@example.test', 'phone' => '5533 4455', 'tags' => 'vip']);
T::eq(302, $r['status'], 'edita la ficha');
T::eq('Ana Lucía R.', Db::val('SELECT name FROM clients WHERE id = ?', [$id]), 'nombre actualizado');

T::section('Notas, etiquetas, bloqueo y archivos');
$admin->get("/admin/clientes/$id");
T::eq(200, $admin->last['status'], 'la ficha carga');
$admin->request('POST', "/admin/clientes/$id/notas", ['_csrf' => $admin->csrf(), 'body' => 'Alérgica a la penicilina']);
T::eq(1, (int) Db::val('SELECT COUNT(*) FROM client_notes WHERE client_id = ?', [$id]), 'agrega una nota privada');
$nid = (int) Db::val('SELECT id FROM client_notes WHERE client_id = ?', [$id]);
$admin->get("/admin/clientes/$id");
T::ok(str_contains($admin->last['body'], 'Alérgica a la penicilina'), 'la nota aparece en la ficha');
$admin->request('POST', "/admin/clientes/$id/etiquetas", ['_csrf' => $admin->csrf(), 'tags' => 'vip, puntual']);
T::eq('vip, puntual', Db::val('SELECT tags FROM clients WHERE id = ?', [$id]), 'guarda etiquetas');
$admin->get('/admin/clientes?etiqueta=puntual');
T::ok(str_contains($admin->last['body'], 'Ana Lucía R.'), 'el filtro por etiqueta la encuentra');
$admin->get('/admin/clientes?etiqueta=inexistente');
T::ok(!str_contains($admin->last['body'], 'Ana Lucía R.'), 'otra etiqueta la excluye');
$admin->request('POST', "/admin/clientes/$id/bloqueo", ['_csrf' => $admin->csrf(), 'blocked' => '1']);
T::eq(1, (int) Db::val('SELECT blocked FROM clients WHERE id = ?', [$id]), 'bloquea al cliente');
$admin->get('/admin/clientes?estado=bloqueados');
T::ok(str_contains($admin->last['body'], 'Ana Lucía R.'), 'aparece en bloqueados');
$admin->request('POST', "/admin/clientes/$id/bloqueo", ['_csrf' => $admin->csrf()]);
T::eq(0, (int) Db::val('SELECT blocked FROM clients WHERE id = ?', [$id]), 'desbloquea');
$tmp = tempnam(sys_get_temp_dir(), 'a1f') . '.txt';
file_put_contents($tmp, "Resumen de la primera consulta.\n");
$admin->get("/admin/clientes/$id");
$r = $admin->request('POST', "/admin/clientes/$id/archivo", ['_csrf' => $admin->csrf(), 'archivo' => new CURLFile($tmp, 'text/plain', 'consulta.txt')]);
T::eq(302, $r['status'], 'sube un archivo');
$f = Db::one("SELECT * FROM files WHERE owner_type = 'client' AND owner_id = ?", [$id]);
T::ok($f && (int) $f['is_public'] === 0, 'archivo privado en la ficha');
$admin->get('/f/' . $f['token']);
T::eq(200, $admin->last['status'], 'se descarga por /f/{token} con sesión');
$anon = new A1Client();
$anon->get('/f/' . $f['token']);
T::eq(403, $anon->last['status'], 'sin sesión no se descarga');
$php = tempnam(sys_get_temp_dir(), 'a1f') . '.php';
file_put_contents($php, '<?php echo 1;');
$admin->get("/admin/clientes/$id");
$admin->request('POST', "/admin/clientes/$id/archivo", ['_csrf' => $admin->csrf(), 'archivo' => new CURLFile($php, 'text/plain', 'x.php')]);
T::eq(1, (int) Db::val("SELECT COUNT(*) FROM files WHERE owner_type = 'client' AND owner_id = ?", [$id]), 'rechaza archivos ejecutables');
$admin->request('POST', "/admin/clientes/$id/notas/$nid/eliminar", ['_csrf' => $admin->csrf()]);
T::eq(0, (int) Db::val('SELECT COUNT(*) FROM client_notes WHERE client_id = ?', [$id]), 'elimina su nota');

T::section('Importar CSV');
$csv = "Nombre;Correo;Teléfono;NIT;Etiquetas\r\nBeatriz Coc;beatriz@example.test;5511 2233;;nuevo\r\nCarlos Tun;correo-malo;5511 2234;;\r\n;sin@nombre.test;;;\r\nAna Lucía R.;ana@example.test;;;importada\r\nBeatriz Repetida;beatriz@example.test;;;\r\nDiego Xol;;4455 6677;987;a, b\r\n";
$tmp = tempnam(sys_get_temp_dir(), 'a1c') . '.csv';
file_put_contents($tmp, mb_convert_encoding($csv, 'ISO-8859-1', 'UTF-8'));
$admin->get('/admin/clientes/importar');
T::eq(200, $admin->last['status'], 'el formulario de importación carga');
$r = $admin->request('POST', '/admin/clientes/importar', ['_csrf' => $admin->csrf(), 'archivo' => new CURLFile($tmp, 'text/csv', 'clientes.csv')]);
T::eq(200, $r['status'], 'vista previa');
T::ok(str_contains($r['body'], 'Beatriz Coc') && str_contains($r['body'], 'Teléfono no válido') === false, 'lee Latin-1 y punto y coma');
T::ok(str_contains($r['body'], 'Correo no válido') && str_contains($r['body'], 'Falta el nombre') && str_contains($r['body'], 'Repetido en el archivo') && str_contains($r['body'], 'Ya existe'), 'valida errores, repetidos y existentes');
T::eq(1, (int) Db::val('SELECT COUNT(*) FROM clients'), 'la vista previa no guarda nada');
preg_match('/name="token" value="([a-f0-9]+)"/', $r['body'], $m);
$r = $admin->request('POST', '/admin/clientes/importar/confirmar', ['_csrf' => $admin->csrf(), 'token' => 'falso']);
T::eq(302, $r['status'], 'token falso no importa');
T::eq(1, (int) Db::val('SELECT COUNT(*) FROM clients'), 'sigue sin guardarse');
$r = $admin->request('POST', '/admin/clientes/importar/confirmar', ['_csrf' => $admin->csrf(), 'token' => $m[1]]);
T::eq(302, $r['status'], 'confirma la importación');
T::ok(Db::val("SELECT COUNT(*) FROM clients WHERE email = 'beatriz@example.test'") == 1, 'crea a Beatriz una sola vez');
T::ok(Db::val("SELECT COUNT(*) FROM clients WHERE name = 'Diego Xol' AND nit = '987'") == 1, 'importa NIT y teléfono sin correo');
T::ok(str_contains((string) Db::val('SELECT tags FROM clients WHERE id = ?', [$id]), 'importada'), 'suma etiquetas a la existente');
T::eq(3, (int) Db::val('SELECT COUNT(*) FROM clients'), 'total correcto tras importar (sin errores)');
$bad = tempnam(sys_get_temp_dir(), 'a1c') . '.csv';
file_put_contents($bad, "Correo,Telefono\nx@example.test,5555 5555\n");
$admin->get('/admin/clientes/importar');
$r = $admin->request('POST', '/admin/clientes/importar', ['_csrf' => $admin->csrf(), 'archivo' => new CURLFile($bad, 'text/csv', 'mal.csv')]);
T::ok($r['status'] === 422 && str_contains($r['body'], 'columna'), 'sin columna Nombre da un error claro');

T::section('Exportar CSV (neutraliza fórmulas)');
Db::insert('clients', ['name' => '=HYPERLINK("http://x.test","clic")', 'email' => 'formula@example.test', 'created_at' => gmdate('Y-m-d H:i:s'), 'updated_at' => gmdate('Y-m-d H:i:s')]);
$admin->get('/admin/clientes/exportar');
T::eq(200, $admin->last['status'], 'exporta');
T::ok(str_contains($admin->last['body'], 'Ana Lucía R.') && str_contains($admin->last['body'], 'Diego Xol'), 'incluye los clientes');
T::ok(str_contains($admin->last['body'], '"\'=HYPERLINK') && !str_contains($admin->last['body'], '"=HYPERLINK'), 'las fórmulas se neutralizan');

T::section('Fusionar duplicados');
$now = gmdate('Y-m-d H:i:s');
$main = $id;
$dupId = Db::insert('clients', ['name' => 'Ana Lucia Ruiz', 'email' => 'ana.ruiz@example.test', 'phone' => null, 'nit' => '555', 'tags' => 'otra', 'noshow_count' => 2, 'blocked' => 1, 'created_at' => $now, 'updated_at' => $now]);
$day = date('Y-m-d', strtotime('+5 day'));
$bk = BookingService::create(['event_id' => 1, 'duration' => 30, 'start' => Tz::localToUtc("$day 10:00:00", 'America/Guatemala'), 'timezone' => 'America/Guatemala', 'name' => 'Ana Lucia Ruiz', 'email' => 'ana.ruiz@example.test', 'consent' => true, 'created_via' => 'admin', 'force' => true]);
$bid = (int) $bk['booking']['id'];
Db::update('bookings', ['client_id' => $dupId], 'id = ?', [$bid]);
Db::insert('client_notes', ['client_id' => $dupId, 'body' => 'nota del duplicado', 'created_at' => $now]);
$admin->get('/admin/clientes/duplicados');
T::eq(200, $admin->last['status'], 'lista de posibles duplicados');
$admin->get("/admin/clientes/fusionar?a=$main&b=$dupId");
T::ok($admin->last['status'] === 200 && str_contains($admin->last['body'], 'Conservar esta ficha'), 'pantalla de fusión');
$r = $admin->request('POST', '/admin/clientes/fusionar', ['_csrf' => $admin->csrf(), 'a' => $main, 'b' => $dupId, 'main' => 999]);
T::eq(302, $r['status'], 'principal inválido no fusiona');
T::eq(1, (int) Db::val('SELECT COUNT(*) FROM clients WHERE id = ?', [$dupId]), 'el duplicado sigue existiendo');
$admin->request('POST', '/admin/clientes/fusionar', ['_csrf' => $admin->csrf(), 'a' => $main, 'b' => $dupId, 'main' => $main]);
T::eq(0, (int) Db::val('SELECT COUNT(*) FROM clients WHERE id = ?', [$dupId]), 'el duplicado desaparece');
T::eq($main, (int) Db::val('SELECT client_id FROM bookings WHERE id = ?', [$bid]), 'las citas pasan al principal');
T::eq(1, (int) Db::val("SELECT COUNT(*) FROM client_notes WHERE client_id = ? AND body = 'nota del duplicado'", [$main]), 'las notas pasan al principal');
$m = Db::one('SELECT * FROM clients WHERE id = ?', [$main]);
T::eq(2, (int) $m['noshow_count'], 'se suman las inasistencias');
T::eq(1, (int) $m['blocked'], 'se conserva el bloqueo');
T::eq('555', $m['nit'], 'se completan datos faltantes (NIT)');
T::ok(str_contains((string) $m['tags'], 'otra') && str_contains((string) $m['tags'], 'vip'), 'se unen las etiquetas');
$r = $admin->request('POST', '/admin/clientes/fusionar', ['_csrf' => $admin->csrf(), 'a' => $main, 'b' => $main, 'main' => $main]);
T::eq(302, $r['status'], 'no se fusiona consigo mismo');

T::section('Privacidad');
$admin->get("/admin/clientes/$main/datos");
T::ok($admin->last['status'] === 200 && str_contains($admin->last['headers'], 'application/json') && is_array(json_decode($admin->last['body'], true)), 'exporta los datos de la persona en JSON');
$admin->get("/admin/clientes/$main");
$r = $admin->request('POST', "/admin/clientes/$main/eliminar", ['_csrf' => $admin->csrf(), 'confirm' => 'eliminar', 'password' => 'Prueba#Segura2026']);
T::eq(1, (int) Db::val('SELECT COUNT(*) FROM clients WHERE id = ? AND anonymized_at IS NULL', [$main]), 'sin la palabra exacta no elimina');
$r = $admin->request('POST', "/admin/clientes/$main/eliminar", ['_csrf' => $admin->csrf(), 'confirm' => 'ELIMINAR', 'password' => 'mala']);
T::eq(1, (int) Db::val('SELECT COUNT(*) FROM clients WHERE id = ? AND anonymized_at IS NULL', [$main]), 'con contraseña incorrecta no elimina');
$r = $admin->request('POST', "/admin/clientes/$main/eliminar", ['_csrf' => $admin->csrf(), 'confirm' => 'ELIMINAR', 'password' => 'Prueba#Segura2026']);
T::eq(302, $r['status'], 'elimina con confirmación fuerte');
T::ok(Db::val('SELECT anonymized_at FROM clients WHERE id = ?', [$main]) !== null, 'los datos quedan anonimizados');
T::done();
