<?php
declare(strict_types=1);

require __DIR__ . '/../lib/T.php';
require __DIR__ . '/../lib/SaHelper.php';
T::boot('sa_workflow', ['profession' => 'medico', 'demo' => true, 'allow_private_http' => true]);

use App\Core\Clock;
use App\Core\Config;
use App\Core\Crypto;
use App\Core\Db;
use App\Core\Settings;
use App\Services\BookingService;
use App\Services\Mailer;
use App\Services\WorkflowService as W;

$dir = SaHelper::workDir('workflow');
SaHelper::startPhp(8175, __DIR__ . '/../lib/sa_receiver.php');
SaHelper::startSmtp(25261, 'plain', $dir . '/smtp.jsonl');
Settings::setMany(['site_base_url' => 'http://agenda.test', 'phone' => '50255551234', 'address' => 'Avenida Reforma 1-23, Zona 9', 'business_name' => 'Clínica Ñ', 'admin_notify_email' => 'dueno@example.test']);

$mkWf = static fn (string $name, array $o = []): int => Db::insert('workflows', $o + [
    'name' => $name, 'trigger_key' => 'booking.created', 'offset_minutes' => 0, 'event_type_id' => null, 'action' => 'email', 'recipient' => 'guest',
    'subject' => null, 'template' => null, 'action_value' => null, 'active' => 1, 'sort_order' => 0, 'created_at' => gmdate('Y-m-d H:i:s'),
]);
$resetWf = static function (): void {
    Db::exec('DELETE FROM workflows');
    Db::exec('DELETE FROM email_queue');
    Db::exec('DELETE FROM message_queue');
    Db::exec('DELETE FROM webhook_deliveries');
};
$ev = SaHelper::makeEvent(['name' => 'Consulta de nutrición', 'location' => 'Sucursal Zona 10']);
$ev2 = SaHelper::makeEvent(['name' => 'Otro servicio']);
$booking = static fn (array $o = [], ?int $e = null): int => SaHelper::makeBooking($e ?? $ev, $o);
$runs = static function (int $bid): array {
    $out = [];
    foreach (Db::all('SELECT r.*, w.name AS wf FROM workflow_runs r JOIN workflows w ON w.id = r.workflow_id WHERE r.booking_id = ? ORDER BY r.id', [$bid]) as $r) {
        $out[$r['wf']] = $r;
    }
    return $out;
};
$display = static fn (int $id): array => BookingService::display((array) BookingService::find($id));
$future = static fn (int $secs): string => gmdate('Y-m-d H:i:s', time() + $secs);
$makeDue = static fn () => Db::exec("UPDATE workflow_runs SET next_attempt_at = ? WHERE status = 'pending'", [gmdate('Y-m-d H:i:s', time() - 5)]);

T::section('Variables en la zona horaria del invitado');
$ny = $display($booking(['starts_at' => '2026-10-12 16:00:00', 'guest_timezone' => 'America/New_York', 'total' => 150, 'price' => 150, 'video_url' => 'https://meet.example.test/x']));
$v = W::variables($ny);
T::eq(['nombre', 'evento', 'fecha', 'hora', 'anfitrion', 'enlace', 'direccion', 'zona', 'videollamada', 'precio', 'telefono_negocio'], array_keys($v), 'las 11 variables del contrato');
T::eq('lunes 12 de octubre de 2026', $v['fecha'], 'fecha en español (Nueva York)');
T::eq('12:00 p. m.', $v['hora'], 'hora en la zona del invitado (Nueva York, UTC-4)');
T::eq('GMT-4 · America/New_York', $v['zona'], 'zona con etiqueta');
T::eq('Q150.00', $v['precio'], 'precio en quetzales');
T::eq('Consulta de nutrición', $v['evento'], 'evento');
T::eq('http://agenda.test/reserva/' . $ny['token'], $v['enlace'], 'enlace absoluto a la cita');
T::eq('Sucursal Zona 10', $v['direccion'], 'dirección del evento si la cita no trae una');
T::eq('+502 5555 1234', $v['telefono_negocio'], 'teléfono del negocio con formato');
T::eq('https://meet.example.test/x', $v['videollamada'], 'videollamada');
$gt = W::variables($display($booking(['starts_at' => '2026-10-13 03:00:00', 'guest_timezone' => 'America/Guatemala'])));
$md = W::variables($display($booking(['starts_at' => '2026-10-13 03:00:00', 'guest_timezone' => 'Europe/Madrid'])));
T::ok($gt['fecha'] === 'lunes 12 de octubre de 2026' && $gt['hora'] === '9:00 p. m.' && $gt['precio'] === 'Sin costo', 'misma cita: Guatemala ve el lunes a las 9:00 p. m.');
T::ok($md['fecha'] === 'martes 13 de octubre de 2026' && $md['hora'] === '5:00 a. m.', 'misma cita: Madrid ve el martes a las 5:00 a. m.');
Db::update('event_types', ['location' => null], 'id = ?', [$ev]);
T::eq('Avenida Reforma 1-23, Zona 9', W::variables($display($booking()))['direccion'], 'sin dirección de cita ni de evento, usa la del negocio');
Db::update('event_types', ['location' => 'Sucursal Zona 10'], 'id = ?', [$ev]);
T::eq('Hola Lucía Méndez, lunes 12 de octubre de 2026 a las 12:00 p. m. [] {}', W::render('Hola {nombre}, {fecha} a las {hora} [{desconocida}] {}', $ny), 'render sustituye y deja vacías las variables desconocidas');
$xss = $display($booking(['guest_name' => '<script>alert(1)</script> & "Co"']));
T::ok(strpos(W::render('{nombre}', $xss), '<script>') === 0, 'render devuelve texto plano (el escape ocurre al armar el HTML)');

T::section('Disparo: ejecuciones inmediatas y programadas');
Db::exec('UPDATE custom_fields SET required = 0');
$presetRuns = (int) Db::val('SELECT COUNT(*) FROM workflows');
T::ok($presetRuns > 0, 'el perfil de profesión instaló flujos de ejemplo (' . $presetRuns . ')');
$demoBooking = BookingService::create(['event_id' => 1, 'duration' => 30, 'start' => gmdate('Y-m-d H:i:00', time() + 10 * 86400), 'timezone' => 'America/Guatemala', 'name' => 'Cliente Integral', 'email' => 'integral@example.test', 'phone' => '55557777', 'consent' => true, 'created_via' => 'admin', 'force' => true]);
$dbId = (int) $demoBooking['booking']['id'];
T::ok(Db::val('SELECT COUNT(*) FROM workflow_runs WHERE booking_id = ?', [$dbId]) > 0, 'BookingService::create → Hooks → WorkflowService::fire creó ejecuciones con los flujos del perfil');
$resetWf();
$mkWf('correo');
$mkWf('wa', ['action' => 'whatsapp']);
$mkWf('host', ['recipient' => 'host', 'subject' => 'Nueva cita de {nombre}', 'template' => 'Atender a {nombre} el {fecha} a las {hora} ({zona}).']);
$mkWf('admin', ['recipient' => 'admin']);
$mkWf('otro_evento', ['event_type_id' => $ev2]);
$mkWf('inactivo', ['active' => 0]);
$mkWf('hook', ['action' => 'webhook', 'action_value' => 'Cita.VIP!']);
$mkWf('rec24', ['trigger_key' => 'booking.before_start', 'offset_minutes' => 1440]);
$mkWf('rec2', ['trigger_key' => 'booking.before_start', 'offset_minutes' => 120, 'action' => 'whatsapp']);
$mkWf('resena', ['trigger_key' => 'booking.after_end', 'offset_minutes' => 60, 'action' => 'review_request']);
$mkWf('cancelado', ['trigger_key' => 'booking.cancelled']);
$mkWf('reprog', ['trigger_key' => 'booking.rescheduled']);
$mkWf('aprob', ['trigger_key' => 'booking.approved']);
$wh = static fn (string $n, string $events): int => Db::insert('webhooks', ['name' => $n, 'url' => 'http://127.0.0.1:8175/rec/' . $n, 'secret' => 'secreto', 'events' => $events, 'active' => 1, 'created_at' => gmdate('Y-m-d H:i:s')]);
$wh('todos', '*');
$wh('solo_creada', 'booking.created');
$wh('vip', 'otro, cita.vip');

$start1 = $future(3 * 86400 + 600);
$b1 = $booking(['starts_at' => $start1]);
W::fire('booking.created', $b1);
$r1 = $runs($b1);
$names = array_keys($r1);
sort($names);
T::eq(['admin', 'correo', 'hook', 'host', 'rec2', 'rec24', 'resena', 'wa'], $names, 'se crean las ejecuciones de los flujos activos del evento (no las de otro evento ni las inactivas)');
T::eq(gmdate('Y-m-d H:i:s', strtotime($start1 . ' UTC') - 86400), $r1['rec24']['scheduled_at'], 'before_start: inicio − offset (24 h)');
T::eq(gmdate('Y-m-d H:i:s', strtotime($start1 . ' UTC') - 7200), $r1['rec2']['scheduled_at'], 'before_start 120 min');
T::eq(gmdate('Y-m-d H:i:s', strtotime($start1 . ' UTC') + 1800 + 3600), $r1['resena']['scheduled_at'], 'after_end: fin + offset');
T::ok(abs(strtotime($r1['correo']['scheduled_at'] . ' UTC') - time()) <= 2 && $r1['correo']['status'] === 'pending' && $r1['rec24']['status'] === 'pending', 'los inmediatos se programan para ahora; todo queda pendiente');

Db::exec('DELETE FROM workflow_runs WHERE booking_id = ?', [$b1]);
Clock::set(time());
W::fire('booking.created', $b1);
$n1 = count($runs($b1));
W::fire('booking.created', $b1);
T::eq($n1, (int) Db::val('SELECT COUNT(*) FROM workflow_runs WHERE booking_id = ?', [$b1]), 'disparar dos veces el mismo evento no duplica ejecuciones (índice único workflow+cita+hora)');
Clock::set(null);

$bNear = $booking(['starts_at' => $future(3 * 3600)]);
W::fire('booking.created', $bNear);
$rn = $runs($bNear);
T::ok($rn['rec24']['status'] === 'skipped' && strpos((string) $rn['rec24']['last_error'], 'ya había pasado') !== false && $rn['rec2']['status'] === 'pending', 'cita en 3 h: el recordatorio de 24 h se omite (skipped) y el de 2 h queda pendiente');
$bSoon = $booking(['starts_at' => $future(1800)]);
W::fire('booking.created', $bSoon);
T::ok($runs($bSoon)['rec2']['status'] === 'skipped', 'cita en 30 min: también se omite el de 2 h');

$bPend = $booking(['starts_at' => $future(5 * 86400), 'status' => 'pending']);
W::fire('booking.created', $bPend);
$rp = array_keys($runs($bPend));
sort($rp);
T::eq(['admin', 'correo', 'hook', 'host', 'wa'], $rp, 'cita pendiente de aprobación: solo mensajes inmediatos, sin recordatorios');
Db::update('bookings', ['status' => 'confirmed'], 'id = ?', [$bPend]);
W::fire('booking.approved', $bPend);
$rp = $runs($bPend);
T::ok(isset($rp['aprob'], $rp['rec24'], $rp['rec2'], $rp['resena']), 'al aprobarla se programan recordatorios y seguimiento y corre el flujo de aprobación');

$bSeries = $booking(['starts_at' => $future(6 * 86400), 'series_index' => 2, 'series_token' => str_repeat('a', 32)]);
W::fire('booking.created', $bSeries);
$rs = array_keys($runs($bSeries));
sort($rs);
T::eq(['rec2', 'rec24', 'resena'], $rs, 'sesión 2 de una serie: sin mensajes inmediatos, pero sí recordatorios');

T::section('Ejecución: correo, WhatsApp y webhook');
$res = W::runDue(100);
T::ok($res['done'] >= 5 && $res['failed'] === 0, 'runDue ejecutó los inmediatos pendientes: ' . json_encode($res));
$r1 = $runs($b1);
T::ok($r1['correo']['status'] === 'done' && (int) $r1['correo']['attempts'] === 1 && $r1['correo']['executed_at'] !== null && $r1['rec24']['status'] === 'pending', 'los inmediatos quedan hechos y los programados siguen pendientes');
$d1 = $display($b1);
$mail = Db::one("SELECT * FROM email_queue WHERE to_email = 'lucia@example.test' AND subject = 'Recibimos tu solicitud'");
T::ok($mail !== null && strpos($mail['body_text'], 'Hola Lucía Méndez') !== false && strpos($mail['body_text'], W::variables($d1)['enlace']) !== false, 'correo al invitado con la plantilla predeterminada y el enlace');
T::ok(strpos($mail['body_html'], 'Clínica Ñ') !== false && strpos($mail['body_html'], 'Ver mi cita') !== false && strpos($mail['body_html'], '<table') !== false, 'el correo usa la plantilla de marca con botón');
$att = json_decode((string) $mail['attachments'], true);
T::ok(($att[0]['name'] ?? '') === 'cita.ics' && strpos(base64_decode($att[0]['b64']), 'UID:ap-' . $d1['token']) !== false, 'la confirmación adjunta cita.ics con el UID de la cita');
$hostMail = Db::one("SELECT * FROM email_queue WHERE subject = ?", ['Nueva cita de Lucía Méndez']);
$vars = W::variables($d1);
T::ok($hostMail !== null && $hostMail['to_email'] === 'admin@test.local' && $hostMail['body_text'] === "Atender a Lucía Méndez el {$vars['fecha']} a las {$vars['hora']} ({$vars['zona']}).", 'correo al anfitrión con asunto y texto propios');
T::ok((int) Db::val("SELECT COUNT(*) FROM email_queue WHERE to_email = 'dueno@example.test' AND body_text LIKE ?", ['%' . W::variables($d1)['enlace'] . '%']) === 1, 'correo al administrador (admin_notify_email)');
$wa = Db::one("SELECT * FROM message_queue WHERE booking_id = ? AND channel = 'whatsapp'", [$b1]);
T::ok($wa !== null && $wa['phone'] === '50255551234' && $wa['status'] === 'pending' && strpos($wa['body'], 'Hola Lucía Méndez') !== false && (int) $wa['workflow_run_id'] === (int) $r1['wa']['id'], 'WhatsApp de un toque: fila pendiente en message_queue con el texto ya redactado');
$del = Db::all("SELECT w.name FROM webhook_deliveries d JOIN webhooks w ON w.id = d.webhook_id WHERE d.event = 'cita.vip' ORDER BY w.name");
T::eq(['todos', 'vip'], array_values(array_unique(array_column($del, 'name'))), 'evento personalizado "cita.vip": coincide "*" y la lista (con espacios), no "booking.created"');
T::ok(Db::val("SELECT COUNT(*) FROM webhook_deliveries d JOIN webhooks w ON w.id = d.webhook_id WHERE w.name = 'solo_creada' AND d.event = 'booking.created'") === 0, 'W::fire no crea entregas de webhook por sí mismo (eso lo hace Hooks)');

T::section('Escape de HTML en correos');
Db::exec('DELETE FROM email_queue');
$bx = $booking(['starts_at' => $future(4 * 86400), 'guest_name' => '<script>alert(1)</script> & "Co"', 'guest_email' => 'xss@example.test']);
Db::update('workflows', ['template' => "Hola {nombre}\n\nVisita https://example.test/a?x=1&y=2 **ya**"], "name = 'correo'");
W::fire('booking.created', $bx);
W::runDue(100);
$m = Db::one("SELECT * FROM email_queue WHERE to_email = 'xss@example.test'");
T::ok($m !== null && strpos($m['body_html'], '<script>alert') === false && strpos($m['body_html'], '&lt;script&gt;alert(1)&lt;/script&gt; &amp; &quot;Co&quot;') !== false, 'el nombre del invitado se escapa en el HTML');
T::ok(strpos($m['body_text'], '<script>alert(1)</script> & "Co"') !== false, 'el texto plano conserva el valor original');
T::ok(strpos($m['body_html'], 'href="https://example.test/a?x=1&amp;y=2"') !== false && strpos($m['body_html'], '<strong>ya</strong>') !== false, 'enlaces y negrita de la plantilla funcionan');

T::section('Sin destinatario, review_request y add_tag');
Db::exec('DELETE FROM workflow_runs');
Db::exec('DELETE FROM workflows');
Db::exec('DELETE FROM email_queue');
Db::exec('DELETE FROM message_queue');
$mkWf('correo');
$mkWf('wa', ['action' => 'whatsapp']);
$bNo = $booking(['starts_at' => $future(86400 * 2), 'guest_email' => null, 'guest_phone' => null]);
W::fire('booking.created', $bNo);
W::runDue();
$rn = $runs($bNo);
T::ok($rn['correo']['status'] === 'skipped' && strpos((string) $rn['correo']['last_error'], 'correo') !== false && $rn['wa']['status'] === 'skipped', 'sin correo ni teléfono: la ejecución se omite con el motivo (no reintenta)');
Db::exec('DELETE FROM workflows');
$mkWf('resena', ['trigger_key' => 'booking.completed', 'action' => 'review_request']);
$mkWf('resena_wa', ['trigger_key' => 'booking.completed', 'action' => 'review_request', 'action_value' => 'whatsapp']);
$mkWf('etiqueta', ['trigger_key' => 'booking.completed', 'action' => 'add_tag', 'action_value' => ' Frecuente ']);
$mkWf('etiqueta_vip', ['trigger_key' => 'booking.completed', 'action' => 'add_tag', 'action_value' => 'VIP']);
$cid = Db::insert('clients', ['name' => 'Lucía Méndez', 'email' => 'lucia@example.test', 'tags' => 'vip,nuevo', 'created_at' => gmdate('Y-m-d H:i:s'), 'updated_at' => gmdate('Y-m-d H:i:s')]);
$bc = $booking(['starts_at' => $future(-7200), 'client_id' => $cid]);
W::fire('booking.completed', $bc);
$res = W::runDue();
$rv = Db::all('SELECT * FROM reviews WHERE booking_id = ?', [$bc]);
T::ok(count($rv) === 1 && $rv[0]['status'] === 'requested' && preg_match('/^[a-f0-9]{32}$/', $rv[0]['token']) === 1 && $rv[0]['client_name'] === 'Lucía Méndez', 'review_request crea una sola reseña "requested" con token');
$rm = Db::one("SELECT * FROM email_queue WHERE to_email = 'lucia@example.test'");
T::ok($rm !== null && strpos($rm['body_text'], 'http://agenda.test/resena/' . $rv[0]['token']) !== false, 'el correo lleva el enlace /resena/{token}');
$rw = Db::one("SELECT * FROM message_queue WHERE booking_id = ?", [$bc]);
T::ok($rw !== null && strpos($rw['body'], '/resena/' . $rv[0]['token']) !== false, 'la variante WhatsApp encola el enlace de reseña');
T::eq('vip,nuevo,Frecuente', (string) Db::val('SELECT tags FROM clients WHERE id = ?', [$cid]), 'add_tag agrega una etiqueta sin duplicar (vip ya existía en otra capitalización)');
Db::exec("UPDATE workflows SET action_value = 'NUEVO' WHERE name = 'etiqueta'");
W::fire('booking.completed', $bc);
Db::exec("UPDATE workflow_runs SET scheduled_at = DATE_SUB(scheduled_at, INTERVAL 1 MINUTE)");
Db::exec("UPDATE workflow_runs SET scheduled_at = DATE_SUB(scheduled_at, INTERVAL 1 DAY) WHERE status = 'pending'");
W::runDue();
T::eq('vip,nuevo,Frecuente', (string) Db::val('SELECT tags FROM clients WHERE id = ?', [$cid]), 'una etiqueta repetida en otra capitalización no se agrega');
T::eq(1, (int) Db::val('SELECT COUNT(*) FROM reviews WHERE booking_id = ?', [$bc]), 'repetir review_request reutiliza la misma reseña');
Db::update('reviews', ['status' => 'approved'], 'booking_id = ?', [$bc]);
$total = (int) Db::val('SELECT COUNT(*) FROM email_queue');
W::fire('booking.completed', $bc);
Db::exec("UPDATE workflow_runs SET scheduled_at = DATE_SUB(scheduled_at, INTERVAL 2 DAY) WHERE status = 'pending'");
W::runDue();
T::eq($total, (int) Db::val('SELECT COUNT(*) FROM email_queue'), 'si la reseña ya fue contestada no se vuelve a pedir');

T::section('set_status con actor de sistema');
Db::exec('DELETE FROM workflows');
Db::exec('DELETE FROM workflow_runs');
$mkWf('cerrar', ['trigger_key' => 'booking.created', 'action' => 'set_status', 'action_value' => 'no_show']);
$mkWf('invalido', ['trigger_key' => 'booking.created', 'action' => 'set_status', 'action_value' => 'hackeado']);
$bs = $booking(['starts_at' => $future(86400)]);
W::fire('booking.created', $bs);
W::runDue();
T::eq('no_show', (string) Db::val('SELECT status FROM bookings WHERE id = ?', [$bs]), 'set_status cambia el estado con BookingService::setStatus');
T::ok(Db::val("SELECT COUNT(*) FROM booking_history WHERE booking_id = ? AND actor LIKE 'Flujo: cerrar'", [$bs]) >= 1, 'el historial registra al actor "Flujo: cerrar"');
$rs = $runs($bs);
T::ok($rs['cerrar']['status'] === 'done' && $rs['invalido']['status'] === 'pending' && strpos((string) $rs['invalido']['last_error'], 'no es válido') !== false, 'un estado inválido falla con mensaje (y se reintenta)');

T::section('Reintentos con WhatsApp Business API contra un receptor falso');
Db::exec('DELETE FROM workflows');
Db::exec('DELETE FROM workflow_runs');
Db::exec('DELETE FROM message_queue');
Config::set('wa_api_base', 'http://127.0.0.1:8175/wa');
Settings::setMany(['wa_api_enabled' => '1', 'wa_api_token' => Crypto::encrypt('TOKEN-SECRETO'), 'wa_api_phone_id' => '123456', 'wa_api_template' => '', 'wa_api_lang' => 'es']);
file_put_contents($dir . '/wa_fail', '2');
$mkWf('api', ['action' => 'whatsapp_api', 'template' => 'Hola {nombre}: tu cita es {fecha}.']);
$ba = $booking(['starts_at' => $future(86400 * 2)]);
W::fire('booking.created', $ba);
$res = W::runDue();
$r = $runs($ba)['api'];
T::ok($res['retry'] === 1 && $r['status'] === 'pending' && (int) $r['attempts'] === 1 && $r['last_error'] !== null, 'intento 1 falla: queda pendiente con el error registrado');
$gap = (strtotime($r['next_attempt_at'] . ' UTC') - time()) / 60;
T::ok($gap > 4 && $gap <= 5.1, 'el segundo intento se espera ~5 min (' . round($gap, 1) . ')');
T::eq(0, W::runDue()['retry'] + W::runDue()['done'], 'antes de la hora no se reintenta');
$mq = Db::all('SELECT * FROM message_queue WHERE booking_id = ?', [$ba]);
T::ok(count($mq) === 1 && $mq[0]['status'] === 'failed' && $mq[0]['channel'] === 'whatsapp_api', 'el mensaje queda registrado como fallido');
$makeDue();
$res = W::runDue();
$r = $runs($ba)['api'];
$gap = (strtotime($r['next_attempt_at'] . ' UTC') - time()) / 60;
T::ok($res['retry'] === 1 && (int) $r['attempts'] === 2 && $gap > 14 && $gap <= 15.1, 'intento 2 falla; el tercero se espera ~15 min (' . round($gap, 1) . ')');
$makeDue();
$res = W::runDue();
$r = $runs($ba)['api'];
T::ok($res['done'] === 1 && $r['status'] === 'done' && (int) $r['attempts'] === 3 && $r['last_error'] === null, 'tras fallar 2 veces, el intento 3 funciona: done con 3 intentos');
$mq = Db::all('SELECT * FROM message_queue WHERE booking_id = ?', [$ba]);
T::ok(count($mq) === 1 && $mq[0]['status'] === 'sent' && $mq[0]['sent_at'] !== null && $mq[0]['last_error'] === null, 'el mismo mensaje pasa a enviado (sin duplicar filas)');
$log = SaHelper::jsonl($dir . '/log_wa.jsonl');
$last = json_decode(end($log)['body'], true);
T::ok(count($log) === 3 && (end($log)['headers']['authorization'] ?? '') === 'Bearer TOKEN-SECRETO' && $last['to'] === '50255551234' && $last['type'] === 'text' && strpos($last['text']['body'], 'Hola Lucía Méndez: tu cita es') === 0, 'el receptor recibió 3 peticiones con token Bearer descifrado y texto redactado');

file_put_contents($dir . '/wa_fail', '99');
$bf = $booking(['starts_at' => $future(86400 * 3)]);
W::fire('booking.created', $bf);
for ($i = 0; $i < 3; $i++) {
    $makeDue();
    $res = W::runDue();
}
$r = $runs($bf)['api'];
T::ok($r['status'] === 'failed' && (int) $r['attempts'] === 3 && $r['last_error'] !== null && $res['failed'] === 1, '3 fallos seguidos: la ejecución queda failed con el último error');
$mq = Db::one('SELECT * FROM message_queue WHERE booking_id = ?', [$bf]);
T::ok($mq['status'] === 'failed' && $mq['last_error'] !== null, 'y el panel puede ver el mensaje fallido');
$makeDue();
T::eq(['done' => 0, 'failed' => 0, 'retry' => 0, 'skipped' => 0], W::runDue(), 'una ejecución failed no se vuelve a intentar');

file_put_contents($dir . '/wa_fail', '0');
file_put_contents($dir . '/wa_mode', 'badtoken');
$bt = $booking(['starts_at' => $future(86400 * 4)]);
W::fire('booking.created', $bt);
W::runDue();
T::ok(strpos((string) $runs($bt)['api']['last_error'], 'token') !== false, 'token rechazado: mensaje amable que explica qué hacer');
file_put_contents($dir . '/wa_mode', '');
Settings::set('wa_api_enabled', '0');
$bd = $booking(['starts_at' => $future(86400 * 5)]);
W::fire('booking.created', $bd);
W::runDue();
$mq = Db::one("SELECT * FROM message_queue WHERE booking_id = ?", [$bd]);
T::ok($runs($bd)['api']['status'] === 'done' && $mq['channel'] === 'whatsapp' && $mq['status'] === 'pending', 'con la API desactivada cae a la cola de un toque');
Settings::set('wa_api_enabled', '1');

T::section('cancelPending, reprogramación y cancelación');
Db::exec('DELETE FROM workflows');
Db::exec('DELETE FROM workflow_runs');
$mkWf('rec24', ['trigger_key' => 'booking.before_start', 'offset_minutes' => 1440]);
$mkWf('resena', ['trigger_key' => 'booking.after_end', 'offset_minutes' => 30]);
$mkWf('aviso_cancel', ['trigger_key' => 'booking.cancelled']);
$mkWf('aviso_reprog', ['trigger_key' => 'booking.rescheduled']);
$bc2 = $booking(['starts_at' => $future(5 * 86400)]);
W::fire('booking.created', $bc2);
T::ok($runs($bc2)['rec24']['status'] === 'pending' && $runs($bc2)['resena']['status'] === 'pending', 'recordatorio y seguimiento programados');
W::cancelPending($bc2);
$rc = $runs($bc2);
T::ok($rc['rec24']['status'] === 'skipped' && $rc['resena']['status'] === 'skipped', 'cancelPending marca skipped las programadas pendientes');
$bc3 = $booking(['starts_at' => $future(6 * 86400)]);
W::fire('booking.created', $bc3);
Db::update('bookings', ['status' => 'cancelled'], 'id = ?', [$bc3]);
W::fire('booking.cancelled', $bc3);
$rc = $runs($bc3);
T::ok($rc['rec24']['status'] === 'skipped' && $rc['aviso_cancel']['status'] === 'pending', 'al cancelar: se omiten las programadas y corre el aviso de cancelación');
$br = $booking(['starts_at' => $future(7 * 86400)]);
W::fire('booking.created', $br);
$old = $runs($br);
$newStart = $future(9 * 86400);
Db::update('bookings', ['starts_at' => $newStart, 'ends_at' => gmdate('Y-m-d H:i:s', strtotime($newStart . ' UTC') + 1800)], 'id = ?', [$br]);
W::fire('booking.rescheduled', $br);
$all = Db::all('SELECT r.status, r.scheduled_at, w.name FROM workflow_runs r JOIN workflows w ON w.id = r.workflow_id WHERE r.booking_id = ? AND w.name = ? ORDER BY r.id', [$br, 'rec24']);
T::ok(count($all) === 2 && $all[0]['status'] === 'skipped' && $all[1]['status'] === 'pending' && $all[1]['scheduled_at'] === gmdate('Y-m-d H:i:s', strtotime($newStart . ' UTC') - 86400), 'reprogramar: el recordatorio viejo se omite y se agenda uno nuevo con la nueva hora');
T::ok(isset($runs($br)['aviso_reprog']), 'y corre el flujo de reprogramación');
$bq = $booking(['starts_at' => $future(86400 * 3)]);
W::fire('booking.created', $bq);
Db::update('workflow_runs', ['scheduled_at' => gmdate('Y-m-d H:i:s', time() - 60), 'next_attempt_at' => null], 'booking_id = ? AND workflow_id = (SELECT id FROM (SELECT id FROM workflows WHERE name = ?) t)', [$bq, 'rec24']);
Db::update('bookings', ['status' => 'cancelled'], 'id = ?', [$bq]);
W::runDue();
T::ok($runs($bq)['rec24']['status'] === 'skipped' && strpos((string) $runs($bq)['rec24']['last_error'], 'confirmada') !== false, 'si la cita se canceló sin pasar por cancelPending, el recordatorio se omite al ejecutarse');
$bq2 = $booking(['starts_at' => $future(-3600), 'ends_at' => $future(-1800), 'status' => 'no_show']);
Db::exec("INSERT INTO workflow_runs (workflow_id, booking_id, scheduled_at, status, created_at) SELECT id, ?, ?, 'pending', ? FROM workflows WHERE name = 'resena'", [$bq2, $future(-60), gmdate('Y-m-d H:i:s')]);
W::runDue();
T::eq('skipped', $runs($bq2)['resena']['status'], 'el seguimiento posterior se omite si la persona no asistió');

T::section('testRun y drain');
Db::exec('DELETE FROM workflows');
Db::exec('DELETE FROM email_queue');
$tw = $mkWf('prueba', ['subject' => 'Cita de {nombre} · {hora}', 'template' => 'Hola {nombre}, nos vemos {fecha}.']);
$bt = $booking(['starts_at' => $future(2 * 86400)]);
$t = W::testRun($tw, $bt);
T::ok($t['ok'] && $t['action'] === 'email' && $t['to'] === 'lucia@example.test' && strpos($t['subject'], 'Cita de Lucía Méndez') === 0 && strpos($t['text'], 'Hola Lucía Méndez, nos vemos') === 0 && !$t['sent'], 'testRun devuelve la vista previa sin enviar');
T::eq(0, (int) Db::val('SELECT COUNT(*) FROM email_queue'), 'testRun no encola nada para el invitado');
Settings::setMany(['smtp_host' => '127.0.0.1', 'smtp_port' => '25261', 'smtp_secure' => 'none', 'smtp_user' => '', 'smtp_pass' => '']);
$t = W::testRun($tw, $bt, true);
$sent = SaHelper::jsonl($dir . '/smtp.jsonl');
T::ok($t['ok'] && $t['sent'] && $t['to'] === 'dueno@example.test' && count($sent) === 1 && $sent[0]['rcpt'] === ['dueno@example.test'], 'testRun con envío manda la prueba SOLO al administrador');
T::ok(strpos(SaHelper::parseEml($sent[0]['data'])[0]['subject'], '=?UTF-8?B?') === 0 || strpos($sent[0]['data'], '[Prueba]') !== false, 'el asunto de la prueba lleva la marca [Prueba]');
T::ok(!W::testRun(999999, $bt)['ok'] && !W::testRun($tw, 999999)['ok'], 'testRun con ids inexistentes: error amable');

T::section('Integración completa: reserva → flujo → correo en cola → cola enviada');
Db::exec('DELETE FROM workflows');
Db::exec('DELETE FROM email_queue');
Db::exec('DELETE FROM workflow_runs');
$mkWf('confirmacion', ['subject' => 'Cita confirmada: {evento}', 'template' => "Hola {nombre}, te esperamos el {fecha} a las {hora}."]);
$int = BookingService::create(['event_id' => 1, 'duration' => 30, 'start' => gmdate('Y-m-d H:i:00', time() + 12 * 86400), 'timezone' => 'America/Guatemala', 'name' => 'Marta Integración', 'email' => 'marta@example.test', 'phone' => '55558888', 'consent' => true, 'created_via' => 'admin', 'force' => true]);
$iid = (int) $int['booking']['id'];
T::eq('pending', (string) Db::val("SELECT status FROM workflow_runs WHERE booking_id = ?", [$iid]), 'la reserva dejó la ejecución pendiente');
W::drain();
T::eq('done', (string) Db::val("SELECT status FROM workflow_runs WHERE booking_id = ?", [$iid]), 'drain ejecutó el flujo');
$q = Db::one("SELECT * FROM email_queue WHERE to_email = 'marta@example.test'");
T::ok($q !== null && $q['status'] === 'sent' && strpos($q['subject'], 'Cita confirmada:') === 0, 'drain también envió la cola: estado sent');
$got = array_values(array_filter(SaHelper::jsonl($dir . '/smtp.jsonl'), static fn (array $m): bool => $m['rcpt'] === ['marta@example.test']));
T::ok(count($got) === 1, 'el servidor SMTP de prueba recibió el correo de la reserva');
[$h, $parts] = SaHelper::parseEml($got[0]['data']);
$types = array_column($parts, 'type');
T::ok(in_array('text/calendar', $types, true) && in_array('text/html', $types, true) && strpos($parts[0]['content'], 'Marta Integración') !== false, 'con texto, HTML y el .ics adjunto');
BookingService::cancel($iid, 'Prueba de cancelación', ['type' => 'user', 'label' => 'Prueba']);
T::ok(Db::val('SELECT status FROM bookings WHERE id = ?', [$iid]) === 'cancelled' && (int) Db::val("SELECT COUNT(*) FROM workflow_runs WHERE booking_id = ? AND status = 'failed'", [$iid]) === 0, 'cancelar la cita por BookingService (Hooks → cancelPending) no deja ejecuciones fallidas');

SaHelper::stopAll();
T::done();
