<?php
declare(strict_types=1);

require __DIR__ . '/../lib/T.php';
require __DIR__ . '/../lib/SaHelper.php';
T::boot('sa_webhook', ['allow_private_http' => true]);

use App\Core\Config;
use App\Core\Crypto;
use App\Core\Db;
use App\Core\Logger;
use App\Core\Settings;
use App\Services\WebhookService as WH;
use App\Services\WhatsAppService as WA;

$dir = SaHelper::workDir('webhook');
SaHelper::startPhp(8176, __DIR__ . '/../lib/sa_receiver.php');
$base = 'http://127.0.0.1:8176';
$now = static fn (): string => gmdate('Y-m-d H:i:s');
$hook = static fn (string $name, string $events, array $o = []): int => Db::insert('webhooks', $o + ['name' => $name, 'url' => $base . '/rec/' . $name, 'secret' => 'secreto-' . $name, 'events' => $events, 'active' => 1, 'created_at' => gmdate('Y-m-d H:i:s')]);
$deliveries = static fn (?string $name = null): array => Db::all('SELECT d.*, w.name FROM webhook_deliveries d JOIN webhooks w ON w.id = d.webhook_id' . ($name ? ' WHERE w.name = ?' : '') . ' ORDER BY d.id', $name ? [$name] : []);
$makeDue = static fn () => Db::exec("UPDATE webhook_deliveries SET next_attempt_at = ? WHERE status = 'pending'", [gmdate('Y-m-d H:i:s', time() - 5)]);

T::section('dispatch: suscripciones y cuerpo');
$hook('todos', '*');
$hook('lista', 'booking.cancelled, booking.created');
$hook('prefijo', 'booking.*');
$hook('otro', 'cita.vip');
$hook('inactivo', '*', ['active' => 0]);
WH::dispatch('booking.created', ['booking' => ['id' => 7, 'nota' => 'Atención ñ ✓']]);
$names = array_column($deliveries(), 'name');
sort($names);
T::eq(['lista', 'prefijo', 'todos'], $names, 'solo los webhooks activos cuyo "events" coincide ("*", lista con espacios, prefijo "booking.*")');
$d = $deliveries('todos')[0];
$body = json_decode($d['payload'], true);
T::ok(preg_match('/^[a-f0-9]{32}$/', $body['id']) === 1 && $body['event'] === 'booking.created' && preg_match('/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\dZ$/', $body['created_at']) === 1 && $body['data']['booking']['id'] === 7, 'cuerpo JSON {id,event,created_at,data}');
T::ok(strpos($d['payload'], 'Atención ñ ✓') !== false, 'UTF-8 sin escapar en el JSON');
T::ok($d['status'] === 'pending' && (int) $d['attempts'] === 0 && $d['event'] === 'booking.created', 'entrega pendiente con el evento');
T::eq(1, count(array_unique(array_column($deliveries(), 'payload'))), 'todos los webhooks de un mismo evento reciben el mismo cuerpo e id');
WH::dispatch('booking.created', ['x' => "\xB1\x31 inválido"]);
T::ok(count($deliveries()) === 6, 'un payload con UTF-8 inválido no rompe ni lanza');
Db::exec('DELETE FROM webhook_deliveries');

T::section('Firma HMAC-SHA256 verificada en el receptor');
WH::dispatch('booking.created', ['booking' => ['id' => 1]]);
$res = WH::deliverDue();
T::eq(['delivered' => 3, 'failed' => 0, 'retry' => 0], $res, 'deliverDue entrega a los tres suscriptores');
$verify = static function (string $secret, string $ts, string $body, string $sig): bool {
    return hash_equals('sha256=' . hash_hmac('sha256', $ts . '.' . $body, $secret), $sig);
};
$log = SaHelper::jsonl($dir . '/log_todos.jsonl')[0];
$h = $log['headers'];
T::eq('booking.created', $h['x-agenda-event'] ?? null, 'cabecera X-Agenda-Event');
T::eq((string) $deliveries('todos')[0]['id'], $h['x-agenda-delivery'] ?? null, 'cabecera X-Agenda-Delivery = id de la entrega');
T::ok(abs((int) $h['x-agenda-timestamp'] - time()) <= 3, 'cabecera X-Agenda-Timestamp (segundos Unix)');
T::ok(strpos($h['x-agenda-signature'], 'sha256=') === 0 && strlen($h['x-agenda-signature']) === 71, 'X-Agenda-Signature con formato sha256=<64 hex>');
T::ok(($h['content-type'] ?? '') === 'application/json' && strpos($h['user-agent'] ?? '', 'AgendaPremium') === 0, 'Content-Type JSON y User-Agent propio');
T::ok($verify('secreto-todos', $h['x-agenda-timestamp'], $log['body'], $h['x-agenda-signature']), 'la firma válida se verifica con el secreto del webhook');
$py = trim((string) shell_exec('python3 -c ' . escapeshellarg('import hmac,hashlib,sys;print("sha256="+hmac.new(sys.argv[1].encode(),(sys.argv[2]+"."+sys.argv[3]).encode(),hashlib.sha256).hexdigest())') . ' secreto-todos ' . escapeshellarg($h['x-agenda-timestamp']) . ' ' . escapeshellarg($log['body'])));
T::eq($py, $h['x-agenda-signature'], 'la firma coincide con la calculada de forma independiente en Python');
T::ok(!$verify('secreto-todos', $h['x-agenda-timestamp'], $log['body'] . ' ', $h['x-agenda-signature']), 'cuerpo alterado → la firma falla');
T::ok(!$verify('secreto-todos', (string) ((int) $h['x-agenda-timestamp'] + 1), $log['body'], $h['x-agenda-signature']), 'marca de tiempo alterada → la firma falla');
T::ok(!$verify('otro-secreto', $h['x-agenda-timestamp'], $log['body'], $h['x-agenda-signature']), 'secreto distinto → la firma falla');
T::ok(!$verify('secreto-todos', $h['x-agenda-timestamp'], $log['body'], substr($h['x-agenda-signature'], 0, -1) . (substr($h['x-agenda-signature'], -1) === '0' ? '1' : '0')), 'firma alterada en un carácter → falla');
$other = SaHelper::jsonl($dir . '/log_lista.jsonl')[0]['headers'];
T::ok($other['x-agenda-signature'] !== $h['x-agenda-signature'], 'cada webhook firma con su propio secreto');
T::eq(WH::sign('k', '123', '{"a":1}'), hash_hmac('sha256', '123.{"a":1}', 'k'), 'WH::sign = HMAC-SHA256 hex de "{timestamp}.{body}"');
$dd = $deliveries('todos')[0];
T::ok($dd['status'] === 'delivered' && (int) $dd['response_code'] === 200 && $dd['response_body'] === 'ok' && $dd['delivered_at'] !== null && (int) $dd['attempts'] === 1, 'se registra código, respuesta, fecha y 1 intento');

T::section('Reintentos con espera creciente');
Db::exec('DELETE FROM webhook_deliveries');
Db::exec('DELETE FROM webhooks');
$hook('flaky', 'cita.x', ['url' => $base . '/rec/flaky?fail=2']);
WH::dispatch('cita.x', ['n' => 1]);
$res = WH::deliverDue();
$d = $deliveries('flaky')[0];
$gap = (strtotime($d['next_attempt_at'] . ' UTC') - time()) / 60;
T::ok($res['retry'] === 1 && $d['status'] === 'pending' && (int) $d['attempts'] === 1 && (int) $d['response_code'] === 500 && $gap > 0.9 && $gap <= 1.1, 'intento 1: 500 → pendiente, reintento en 1 min (' . round($gap, 2) . ')');
T::eq(['delivered' => 0, 'failed' => 0, 'retry' => 0], WH::deliverDue(), 'antes de la hora no se reintenta');
$makeDue();
WH::deliverDue();
$d = $deliveries('flaky')[0];
$gap = (strtotime($d['next_attempt_at'] . ' UTC') - time()) / 60;
T::ok((int) $d['attempts'] === 2 && $gap > 4.9 && $gap <= 5.1, 'intento 2: reintento en 5 min (' . round($gap, 2) . ')');
$makeDue();
$res = WH::deliverDue();
$d = $deliveries('flaky')[0];
T::ok($res['delivered'] === 1 && $d['status'] === 'delivered' && (int) $d['attempts'] === 3 && (int) $d['response_code'] === 200, 'intento 3 funciona: entregado');
$bodies = array_unique(array_map(static fn (array $l): string => $l['body'], SaHelper::jsonl($dir . '/log_flaky.jsonl')));
T::ok(count($bodies) === 1, 'el cuerpo (y su id) se conserva idéntico en cada reintento');

Db::exec('DELETE FROM webhook_deliveries');
Db::exec('DELETE FROM webhooks');
$hook('caido', 'cita.y', ['url' => $base . '/rec/caido?fail=99']);
WH::dispatch('cita.y', []);
$expected = [1, 5, 30, 120, 720];
foreach ($expected as $i => $mins) {
    WH::deliverDue();
    $d = $deliveries('caido')[0];
    $gap = (strtotime($d['next_attempt_at'] . ' UTC') - time()) / 60;
    T::ok($d['status'] === 'pending' && (int) $d['attempts'] === $i + 1 && abs($gap - $mins) < 1.1, 'fallo ' . ($i + 1) . ': siguiente intento en ' . round($gap) . ' min (esperado ' . $mins . ')');
    $makeDue();
}
$res = WH::deliverDue();
$d = $deliveries('caido')[0];
T::ok($res['failed'] === 1 && $d['status'] === 'failed' && (int) $d['attempts'] === 6 && (int) $d['response_code'] === 500, 'sexto fallo: la entrega queda failed (6 intentos)');
$makeDue();
T::eq(['delivered' => 0, 'failed' => 0, 'retry' => 0], WH::deliverDue(), 'una entrega failed no se reintenta');

T::section('Webhooks desactivados, destinos prohibidos y respuestas raras');
Db::exec('DELETE FROM webhook_deliveries');
Db::exec('DELETE FROM webhooks');
$h1 = $hook('apagado', '*');
WH::dispatch('cita.z', []);
Db::update('webhooks', ['active' => 0], 'id = ?', [$h1]);
$res = WH::deliverDue();
T::ok($res['failed'] === 1 && strpos((string) $deliveries('apagado')[0]['response_body'], 'desactivado') !== false, 'un webhook desactivado después del dispatch no se llama');
Db::exec('DELETE FROM webhook_deliveries');
Db::exec('DELETE FROM webhooks');
$hook('interno', '*', ['url' => 'http://169.254.169.254/latest/meta-data/']);
$hook('redir', '*', ['url' => $base . '/redirect?to=' . rawurlencode('http://127.0.0.1:8176/rec/destino')]);
Config::set('allow_private_http', false);
WH::dispatch('cita.z', []);
$res = WH::deliverDue();
$d = $deliveries('interno')[0];
T::ok($res['retry'] === 2 && $d['status'] === 'pending' && $d['response_code'] === null && strpos((string) $d['response_body'], 'internas o privadas') !== false, 'SSRF: un webhook a una IP interna no se llama y se anota el motivo');
Config::set('allow_private_http', true);
Db::exec('DELETE FROM webhook_deliveries');
WH::dispatch('cita.z', []);
$makeDue();
WH::deliverDue();
T::ok(!is_file($dir . '/log_destino.jsonl') && $deliveries('redir')[0]['status'] === 'pending' && (int) $deliveries('redir')[0]['response_code'] === 302, 'las redirecciones del destino no se siguen (302 cuenta como fallo)');

T::section('bookingPayload');
$ev = SaHelper::makeEvent(['name' => 'Consulta ñ']);
$bid = SaHelper::makeBooking($ev, ['starts_at' => '2026-10-12 16:00:00', 'notes' => 'Llevar estudios', 'internal_note' => 'SECRETO INTERNO', 'total' => 150, 'price' => 150, 'utm_source' => 'fb']);
Db::insert('booking_answers', ['booking_id' => $bid, 'label' => '¿Primera vez?', 'value' => 'Sí']);
$p = WH::bookingPayload($bid);
T::eq(['booking', 'client', 'event', 'host', 'hosts', 'answers'], array_keys($p), 'estructura del payload');
T::ok($p['booking']['id'] === $bid && $p['booking']['status'] === 'confirmed' && $p['booking']['starts_at'] === '2026-10-12T16:00:00Z' && $p['booking']['ends_at'] === '2026-10-12T16:30:00Z' && $p['booking']['total'] === 150.0, 'datos de la cita con fechas ISO en UTC');
T::ok($p['client']['name'] === 'Lucía Méndez' && $p['client']['email'] === 'lucia@example.test' && $p['event']['name'] === 'Consulta ñ' && $p['host']['email'] === 'admin@test.local' && count($p['hosts']) === 1, 'cliente, evento y anfitrión');
T::eq([['label' => '¿Primera vez?', 'value' => 'Sí']], $p['answers'], 'respuestas del formulario');
T::ok(strpos((string) json_encode($p), 'SECRETO INTERNO') === false && !array_key_exists('token', $p['booking']) && !array_key_exists('internal_note', $p['booking']), 'bookingPayload no incluye token ni nota interna');
T::eq([], WH::bookingPayload(999999), 'cita inexistente → arreglo vacío');

T::section('WhatsApp: enlace de un toque');
T::eq('https://wa.me/50255551234?text=Hola%20mundo%20%C3%B1%3F%26%0AL%C3%ADnea%202', WA::link('+502 5555-1234', "Hola mundo ñ?&\nLínea 2"), 'link con dígitos y texto codificado');
T::eq('https://wa.me/50255551234?text=x', WA::link('55551234', 'x'), 'teléfono de 8 dígitos recibe 502');
T::eq('https://wa.me/14155550123?text=x', WA::link('+1 (415) 555-0123', 'x'), 'número internacional se conserva');

T::section('WhatsApp: API Cloud contra un receptor falso');
Config::set('wa_api_base', $base . '/wa');
$r = WA::send('55551234', 'Hola');
T::ok(!$r['ok'] && strpos((string) $r['error'], 'Falta configurar') !== false, 'sin configuración: mensaje amable');
Settings::setMany(['wa_api_enabled' => '1', 'wa_api_token' => 'TOKEN-PLANO', 'wa_api_phone_id' => '99887766', 'wa_api_template' => '', 'wa_api_lang' => 'es']);
$r = WA::send('abc', 'Hola');
T::ok(!$r['ok'] && strpos((string) $r['error'], 'teléfono') !== false, 'teléfono inválido');
file_put_contents($dir . '/wa_fail', '0');
$r = WA::send('+502 5555-1234', "Hola José\nTu cita es mañana ✓");
$log = SaHelper::jsonl($dir . '/log_wa.jsonl');
$req = end($log);
$j = json_decode($req['body'], true);
T::ok($r['ok'] && $r['id'] === 'wamid.TEST1' && $req['path'] === '/wa/99887766/messages', 'envío correcto a /{phone_id}/messages; devuelve el id del mensaje');
T::ok($req['headers']['authorization'] === 'Bearer TOKEN-PLANO' && $req['headers']['content-type'] === 'application/json', 'cabeceras Authorization Bearer y JSON');
T::ok($j['messaging_product'] === 'whatsapp' && $j['to'] === '50255551234' && $j['type'] === 'text' && $j['text']['body'] === "Hola José\nTu cita es mañana ✓", 'mensaje de texto con destinatario normalizado y UTF-8 intacto');
Settings::set('wa_api_token', Crypto::encrypt('TOKEN-CIFRADO'));
WA::send('55551234', 'x');
$log = SaHelper::jsonl($dir . '/log_wa.jsonl');
T::eq('Bearer TOKEN-CIFRADO', end($log)['headers']['authorization'], 'token cifrado (v1:) se descifra');
Settings::setMany(['wa_api_template' => 'recordatorio_cita', 'wa_api_lang' => 'es_MX']);
WA::send('55551234', "Hola\n\nTu cita   es hoy");
$log = SaHelper::jsonl($dir . '/log_wa.jsonl');
$j = json_decode(end($log)['body'], true);
T::ok($j['type'] === 'template' && $j['template']['name'] === 'recordatorio_cita' && $j['template']['language']['code'] === 'es_MX' && $j['template']['components'][0]['parameters'][0]['text'] === 'Hola · Tu cita es hoy', 'con plantilla: type=template, idioma y variable {{1}} en una sola línea');
Settings::set('wa_api_template', '');
file_put_contents($dir . '/wa_mode', 'badtoken');
$r = WA::send('55551234', 'x');
T::ok(!$r['ok'] && strpos((string) $r['error'], 'token') !== false, 'error 401/190: explica que el token no sirve');
file_put_contents($dir . '/wa_mode', '');
file_put_contents($dir . '/wa_fail', '99');
$r = WA::send('55551234', 'x');
T::ok(!$r['ok'] && strpos((string) $r['error'], 'temporal') !== false && $r['id'] === null, 'error 500: se informa sin lanzar');
$tail = implode("\n", Logger::tail(200));
T::ok(strpos($tail, 'TOKEN-PLANO') === false && strpos($tail, 'TOKEN-CIFRADO') === false, 'el token nunca se escribe en el log');
Settings::set('wa_api_phone_id', 'no-es-numero');
T::ok(!WA::send('55551234', 'x')['ok'], 'identificador del número inválido se rechaza antes de llamar');
Config::set('allow_private_http', false);
Settings::set('wa_api_phone_id', '99887766');
$r = WA::send('55551234', 'x');
T::ok(!$r['ok'] && strpos((string) $r['error'], 'internas o privadas') !== false, 'la API también pasa por SafeHttp (SSRF)');
$const = new ReflectionClassConstant(WA::class, 'DEFAULT_BASE');
T::eq('https://graph.facebook.com/v20.0', $const->getValue(), 'la base por defecto es la API oficial (wa_api_base solo para pruebas)');

SaHelper::stopAll();
T::done();
