<?php
declare(strict_types=1);
/** Panel: 2FA TOTP, cambio de contraseña, diagnóstico, prueba de IA, ajustes (incl. cPanel), filtros y búsqueda. */
require __DIR__ . '/lib.php';
define('S5_ROOT', '/tmp/s5test/portal');
require_once S5_ROOT . '/app/Core/Totp.php';
use S5\Core\Totp;
reset_limits();
t_ok(Totp::code('GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ', 59) === '287082', 'TOTP: vector de prueba RFC 6238 (T=59 → 287082)');
$a = new Client(); $a->page('/admin/login');
$a->form('/admin/login', ['email' => 'dueno@servicom.test', 'password' => 'Contrasena-Segura-123']);
$r = $a->page('/admin/cuenta'); t_ok($r['status'] === 200 && str_contains($r['body'], 'Verificación en dos pasos'), 'pantalla de cuenta');
$a->form('/admin/cuenta', ['accion' => 'totp_iniciar']);
$r = $a->page('/admin/cuenta'); preg_match('/<code[^>]*>([A-Z2-7]{32})<\/code>/', $r['body'], $m); $secret = $m[1] ?? '';
t_ok(strlen($secret) === 32, 'se genera la clave TOTP');
$a->form('/admin/cuenta', ['accion' => 'totp_activar', 'code' => '000000']);
t_ok(mysql_val("SELECT totp_enabled FROM s5test.s5_users LIMIT 1") === '0', 'código incorrecto no activa 2FA');
$a->form('/admin/cuenta', ['accion' => 'totp_activar', 'code' => Totp::code($secret)]);
t_ok(mysql_val("SELECT totp_enabled FROM s5test.s5_users LIMIT 1") === '1', '2FA activado con código válido');
t_ok(!str_contains((string) mysql_val("SELECT totp_secret FROM s5test.s5_users LIMIT 1"), $secret), 'la clave TOTP se guarda cifrada');
$a->form('/logout-no-existe', []);
$out = new Client(); $out->page('/admin/login');
$r = $out->form('/admin/login', ['email' => 'dueno@servicom.test', 'password' => 'Contrasena-Segura-123']);
$r2 = $out->page('/admin'); t_ok($r2['status'] === 302, 'con 2FA, la contraseña sola NO da acceso');
$pg = $out->page('/admin/login'); t_ok(str_contains($pg['body'], 'Código de verificación'), 'se pide el código de verificación');
$r = $out->form('/admin/login', ['code' => '111111']); $r2 = $out->page('/admin'); t_ok($r2['status'] === 302, 'código incorrecto rechazado');
$out->page('/admin/login'); $r = $out->form('/admin/login', ['code' => Totp::code($secret)]); $r2 = $out->page('/admin');
t_ok($r2['status'] === 200 && str_contains($r2['body'], 'Resumen'), 'código correcto → acceso');
$out->form('/admin/cuenta', ['accion' => 'totp_quitar', 'actual' => 'Contrasena-Segura-123']);
t_ok(mysql_val("SELECT totp_enabled FROM s5test.s5_users LIMIT 1") === '0', '2FA se puede desactivar con la contraseña');
echo "== Contraseña\n";
$out->form('/admin/cuenta', ['accion' => 'password', 'actual' => 'mala', 'nueva' => 'OtraContrasenaSegura1']);
t_ok(!password_verify('OtraContrasenaSegura1', (string) mysql_val("SELECT pass_hash FROM s5test.s5_users LIMIT 1")), 'actual incorrecta no cambia');
$out->form('/admin/cuenta', ['accion' => 'password', 'actual' => 'Contrasena-Segura-123', 'nueva' => 'corta']);
t_ok(!password_verify('corta', (string) mysql_val("SELECT pass_hash FROM s5test.s5_users LIMIT 1")), 'nueva corta rechazada');
$out->form('/admin/cuenta', ['accion' => 'password', 'actual' => 'Contrasena-Segura-123', 'nueva' => 'Contrasena-Segura-123']);
echo "== Diagnóstico y prueba de IA\n";
$d = $out->page('/admin/diagnostico'); t_ok($d['status'] === 200 && str_contains($d['body'], 'Versión de PHP') && str_contains($d['body'], 'paquete base'), 'diagnóstico completo');
t_ok(!str_contains($d['body'], 'token_secreto') && !str_contains($d['body'], 's5adminpass'), 'el diagnóstico no filtra secretos');
$r = $out->form('/admin/diagnostico', ['accion' => 'ia']); t_ok(str_contains($r['body'], 'La API respondió correctamente'), 'prueba mínima de IA OK (mock)');
$r = $out->form('/admin/diagnostico', ['accion' => 'cron']); t_ok(str_contains($r['body'], 'borrados'), 'ejecutar cron desde diagnóstico');
echo "== Ajustes\n";
$s = $out->page('/admin/ajustes'); t_ok($s['status'] === 200 && !str_contains($s['body'], 'sk-test-mock') && str_contains($s['body'], 'guardada'), 'la clave de IA no se muestra (solo «guardada»)');
$out->form('/admin/ajustes', ['precio_info' => '1300', 'precio_tienda' => '1800', 'precio_tarjeta' => '800', 'reservados' => 'foo', 'banco_cuenta' => '999', 'dominio_base' => 'servicom.test', 'portal_sub' => 'crear', 'ai_key' => '__guardado__']);
t_ok(mysql_val("SELECT v FROM s5test.s5_settings WHERE k='precio_info'") === '1300', 'precios editables');
$res = (string) mysql_val("SELECT v FROM s5test.s5_settings WHERE k='reservados'");
t_ok(str_contains($res, 'www') && str_contains($res, 'cpw') && str_contains($res, 'ctv') && str_contains($res, 'foo'), 'reservados esenciales siempre se conservan');
$h = (new Client())->page('/'); t_ok(str_contains($h['body'], 'Q1,300') && str_contains($h['body'], 'Q1,800'), 'los precios del portal siguen los ajustes');
$out->form('/admin/ajustes', ['precio_info' => '1250', 'precio_tienda' => '1750', 'precio_tarjeta' => '750']);
$out->form('/admin/ajustes', ['dominio_base' => 'no es dominio']); t_ok(mysql_val("SELECT v FROM s5test.s5_settings WHERE k='dominio_base'") === 'servicom.test', 'dominio base inválido rechazado');
t_ok(mysql_val("SELECT is_secret FROM s5test.s5_settings WHERE k='ai_key'") === '1' && !str_contains((string) mysql_val("SELECT v FROM s5test.s5_settings WHERE k='ai_key'"), 'sk-test'), 'clave de IA cifrada en la base de datos');
echo "== Hosting único (cPanel en Ajustes), pedidos, filtros\n";
$hs = $out->page('/admin/hostings'); t_ok($hs['status'] === 404, 'ya no existe la pantalla Hostings (404)');
$st = $out->page('/admin/ajustes'); t_ok(str_contains($st['body'], 'cPanel (hosting de las webs de clientes)') && !str_contains($st['body'], 'name="host_id"'), 'Ajustes tiene la sección cPanel y no hay selector de hosting');
t_ok((int) mysql_val('SELECT COUNT(*) FROM s5test.s5_hosts') === 1, 'hay un único hosting configurado');
$dm = $out->page('/admin/demos'); t_ok(!str_contains($dm['body'], 'host_id') && !str_contains($dm['body'], 'Hosting'), 'Demos sin selector de hosting');
$out->form('/admin/ajustes', ['cp_host' => 'localhost', 'cp_port' => '2083', 'cp_user' => 'otra_cuenta', 'cp_token' => '', 'cp_home' => '/home/otra', 'cp_webs' => '/tmp/s5test/webs']);
$kind = mysql_val('SELECT kind FROM s5test.s5_hosts LIMIT 1'); t_ok($kind === 'sim', 'el simulador de pruebas no se altera (tipo ' . $kind . ')');
$out->form('/admin/ajustes', ['cp_user' => 'x', 'cp_host' => 'localhost', 'cp_webs' => 'relativa/ruta']); t_ok(mysql_val("SELECT v FROM s5test.s5_settings WHERE k='webs_path'") === '/tmp/s5test/webs', 'una ruta de webs relativa no se acepta (se conserva la anterior)');
$p = $out->page('/admin/pedidos?q=' . rawurlencode("' OR 1=1 --")); t_ok($p['status'] === 200 && !str_contains($p['body'], 'SQL'), 'búsqueda resistente a inyección');
$p = $out->page('/admin/pedidos?estado=publicada&plan=info&q=a'); t_ok($p['status'] === 200, 'filtros combinados');
$p = $out->page('/admin/pedido/999999'); t_ok($p['status'] === 404, 'pedido inexistente 404');
$out->form('/admin/logout', []);
$p = $out->page('/admin/pedidos'); t_ok($p['status'] === 302, 'cierre de sesión');
echo "\nPanel: " . ($GLOBALS['__t_n'] - $GLOBALS['__t_fail']) . "/" . $GLOBALS['__t_n'] . " OK\n";
exit(($GLOBALS['__t_fail'] ?? 0) ? 1 : 0);
