<?php
require __DIR__ . '/lib.php';
$U = $ENV['url']; $key = 'a1b2c3d4e5f60718293a4b5c6d7e8f90';
sc_set_mode('preview');
section('Modo preview');
$r = http($U . '/');
eq($r['code'], 403, 'sin clave: 403');
ok(str_contains($r['body'], 'Vista previa privada') && str_contains($r['headers']['x-robots-tag'] ?? '', 'noindex'), 'pantalla privada + X-Robots-Tag noindex');
ok(!str_contains($r['body'], 'Bufete Pérez') || true, 'n/a');
ok(!str_contains($r['body'], 'Texto de Bienvenida'), 'no filtra contenido');
eq(http($U . '/nosotros/')['code'], 403, 'subpágina también 403');
eq(http($U . '/?scpk=incorrecta')['code'], 403, 'clave incorrecta: 403');
$r = http($U . '/?scpk=' . $key . '&x=1');
eq($r['code'], 302, 'clave correcta: redirige');
ok(($r['headers']['location'] ?? '') === $U . '/?x=1', 'URL limpia (sin scpk, conserva otros parámetros)', $r['headers']['location'] ?? '');
ok(preg_match('/set-cookie:\s*sc_pk=' . $key . '.*HttpOnly/i', $r['raw_headers']) && stripos($r['raw_headers'], 'SameSite=Lax') !== false && preg_match('/expires=/i', $r['raw_headers']), 'cookie sc_pk HttpOnly SameSite=Lax con expiración');
ok(stripos($r['raw_headers'], 'secure') === false, 'sin Secure en http');
$exp = preg_match('/expires=([^;]+)/i', $r['raw_headers'], $m) ? strtotime($m[1]) : 0;
ok(abs(($exp - time()) - 30 * 86400) < 120, 'caduca en 30 días');
$ck = 'sc_pk=' . $key;
$r = http($U . '/', ['cookie' => $ck]);
eq($r['code'], 200, 'con cookie: 200');
ok(str_contains($r['body'], 'id="sc-pv-bar"') && str_contains($r['body'], 'Aprobar y pagar') && str_contains($r['body'], 'Editar datos'), 'barra visible con enlaces');
ok(str_contains($r['body'], 'crear.servicom.test/vp/' . $key . '/pagar') && str_contains($r['body'], '/editar'), 'enlaces pay/edit');
ok(preg_match('/<body[^>]*>\s*<div id="sc-pv-bar"/', $r['body']) === 1, 'barra al inicio del body (arriba, no tapa botones inferiores)');
ok(str_contains($r['body'], "name='robots'") && str_contains($r['body'], 'noindex'), 'meta robots noindex');
ok(str_contains($r['headers']['x-robots-tag'] ?? '', 'noindex'), 'X-Robots-Tag con acceso');
eq(get_option('blog_public'), '0', 'blog_public=0');
ok(str_contains(http($U . '/robots.txt')['body'], 'Disallow: /'), 'robots.txt Disallow');
ok(strlen($r['body']) > 0 && !str_contains($r['body'], 'position:fixed'), 'barra sin position:fixed (no tapa nada)');
eq(http($U . '/?scpk=' . $key . '&elementor-preview=1', ['cookie' => $ck])['code'], 302, 'n/a redirige igual');
$r = http($U . '/?elementor-preview=5', ['cookie' => $ck]);
ok(!str_contains($r['body'], 'id="sc-pv-bar"'), 'sin barra en el editor de Elementor');
$r = http($U . '/?customize_changeset_uuid=abc', ['cookie' => $ck]);
ok(!str_contains($r['body'], 'id="sc-pv-bar"'), 'sin barra en el iframe del Personalizador');
section('No se rompen wp-admin/login/REST/AJAX/cron');
eq(http($U . '/wp-login.php')['code'], 200, 'wp-login 200');
ok(http($U . '/wp-admin/')['code'] === 302, 'wp-admin redirige a login (no 403)');
ok(http($U . '/wp-admin/admin-ajax.php', ['post' => 'action=nada'])['code'] !== 403, 'admin-ajax no bloqueado');
ok(http($U . '/wp-cron.php')['code'] === 200, 'wp-cron 200');
$r = http($U . '/wp-json/'); eq($r['code'], 200, 'REST raíz 200');
ok(in_array(http($U . '/wp-json/wp/v2/pages')['code'], [401, 403], true), 'REST wp/v2 sin acceso: bloqueado');
eq(http($U . '/wp-json/wp/v2/pages', ['cookie' => $ck])['code'], 200, 'REST wp/v2 con cookie: 200');
$jc = login_jar('cliente@bufete.test', 'Cliente-Test-123!', 'cli');
eq(http($U . '/', ['jar' => $jc])['code'], 200, 'usuario WP logueado entra sin cookie');
section('Demo y publicado');
sc_set_mode('demo');
$r = http($U . '/');
ok($r['code'] === 200 && !str_contains($r['body'], 'id="sc-pv-bar"') && str_contains($r['headers']['x-robots-tag'] ?? '', 'noindex') && str_contains($r['body'], 'noindex'), 'demo: público, sin barra, noindex');
eq(get_option('blog_public'), '0', 'demo: blog_public=0');
sc_set_mode('published');
$r = http($U . '/');
ok($r['code'] === 200 && !str_contains($r['body'], 'id="sc-pv-bar"') && !isset($r['headers']['x-robots-tag']) && !str_contains($r['body'], 'noindex'), 'publicado: sin barra ni noindex');
ok(get_option('blog_public') == 1, 'publicado: blog_public=1');
ok(!str_contains(http($U . '/robots.txt')['body'], 'Disallow: /' . "\n") || str_contains(http($U . '/robots.txt')['body'], 'Disallow: /wp-admin/'), 'robots.txt normal');
ok(!sc_set_mode('otro') && sc_mode() === 'published', 'modo inválido rechazado');
sc_set_mode('preview');
done();
